### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  id: VisualBasicSettingsValueSerializer
  children:
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: VisualBasicSettingsValueSerializer
  nameWithType: VisualBasicSettingsValueSerializer
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  type: Class
  summary: "Сериализует <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> экземпляров в XAML."
  remarks: "VisualBasicSettingsValueSerializer выполняет сериализацию выражений Visual Basic в XAML."
  syntax:
    content: 'public sealed class VisualBasicSettingsValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  langs:
  - csharp
  name: VisualBasicSettingsValueSerializer()
  nameWithType: VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer()
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: "Инициализирует новый экземпляр <xref href=&quot;Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer&quot;> </xref> класса."
  syntax:
    content: public VisualBasicSettingsValueSerializer ();
    parameters: []
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: VisualBasicSettingsValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: "Определяет, является ли указанный <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> экземпляр может быть преобразован в <xref:System.String>.</xref:System.String>"
  remarks: "При вызове этот метод повышает указанный <xref:Microsoft.VisualBasic.Activities.VisualBasicSettings>экземпляр объявления пространств имен и добавляет их в контекст сериализации.</xref:Microsoft.VisualBasic.Activities.VisualBasicSettings>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Преобразуемое значение."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Контекстная информация, используемая при выполнении преобразования."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Если указанный <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> экземпляр может быть преобразован в <xref:System.String>; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: VisualBasicSettingsValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: "Преобразует указанный <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> экземпляра в <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Преобразуемое значение."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Контекстная информация, используемая при выполнении преобразования."
    return:
      type: System.String
      description: "Строковое представление <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> экземпляра."
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: VisualBasicSettingsValueSerializer()
  nameWithType: VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer()
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer()
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: VisualBasicSettingsValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: VisualBasicSettingsValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: VisualBasicSettingsValueSerializer
  nameWithType: VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: VisualBasicSettingsValueSerializer.CanConvertToString
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: VisualBasicSettingsValueSerializer.ConvertToString
