### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  id: AuthenticationMode
  children:
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  langs:
  - csharp
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  type: Enum
  summary: "Указывает, как приложение Visual Basic выполняет проверку подлинности пользователя для <xref uid=&quot;langword_csharp_My.User&quot; name=&quot;My.User&quot; href=&quot;&quot;> </xref> объекта."
  remarks: "Режим проверки подлинности для приложения можно задать, передав одно из значений этого перечисления <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A>конструктор.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A> Дополнительные сведения см. в разделе [расширение модели приложения Visual Basic](~/add/includes/ajax-current-ext-md.md).       Приложение Visual Basic, который использует модель приложения Visual Basic можно указать, использует ли проверка подлинности Windows или нестандартную проверку подлинности. Также можно настроить режим проверки подлинности в интегрированной среде разработки Visual Studio. Дополнительные сведения см. в разделе [страница &quot;приложение&quot; в конструкторе проектов (Visual Basic)](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public enum AuthenticationMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  id: ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "&lt;Xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A&gt; конструктор не инициализирует участника для основного потока приложения. Приложение должно инициализировать участника для основного потока приложения."
  syntax:
    content: ApplicationDefined
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  id: Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "&lt;Xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A&gt; конструктор инициализирует участника для основного потока приложения с данными пользователя Windows текущего пользователя."
  syntax:
    content: Windows
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
