### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  id: NoStartupFormException
  children:
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: NoStartupFormException
  nameWithType: NoStartupFormException
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  type: Class
  summary: "Это исключение возникает в модели приложения Visual Basic при <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm*>свойство не задано.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm*>"
  remarks: "Модель приложения Visual Basic необходимо, чтобы приложение <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A>свойство перед выполнением <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A>метод.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A> Если свойство не задано, то модель приложения Visual Basic вызывает это исключение. Дополнительные сведения см. в разделе [расширение модели приложения Visual Basic](~/add/includes/ajax-current-ext-md.md).      Настроек [!NOTE] настроек сведения о настройке начальной формы с помощью **конструктора проектов**, в разделе [страница &quot;приложение&quot; в конструкторе проектов (Visual Basic)](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class NoStartupFormException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Инициализирует новый экземпляр <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> класса."
  remarks: "Модель приложения Visual Basic необходимо, чтобы приложение <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A>свойство перед выполнением <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A>метод.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A> Если свойство не задано, то модель приложения Visual Basic вызывает это исключение. Дополнительные сведения см. в разделе [расширение модели приложения Visual Basic](~/add/includes/ajax-current-ext-md.md).       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>.</xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>      |||   |-|-|   | Свойство | Значение |   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic). |   | <xref:System.Exception.Message%2A>| Строка локализованного сообщения об ошибке. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Инициализирует новый экземпляр <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> класса с указанным сообщением об ошибке."
  remarks: "Содержимое `message` параметр должен быть понятным пользователю. Код, вызывающий этот конструктор, должен убедиться, что эта строка локализована для текущего языка и региональных параметров системы.       <xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>наследует от <xref:System.Exception>.</xref:System.Exception></xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException> Этот конструктор задает свойства <xref:System.Exception>объекта, как показано в следующей таблице.</xref:System.Exception>      |||   |-|-|   | Свойство | Значение |   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic) |   | <xref:System.Exception.Message%2A>| `message` Строка. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, описывающее ошибку."
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Инициализирует новый экземпляр <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> сериализованными данными."
  remarks: "Данный конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке."
  syntax:
    content: protected NoStartupFormException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> Объект, содержащий сериализованные данные объекта о вызываемом исключении."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>Объект, содержащий контекстные сведения об источнике или назначении.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Инициализирует новый экземпляр <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> класса с указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение."
  remarks: "Содержимое `message` параметр должен быть понятным пользователю. Код, вызывающий этот конструктор, должен убедиться, что эта строка локализована для текущего языка и региональных параметров системы.       Исключение, созданное как прямой результат предыдущего исключения, должно содержать ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Свойство возвращает то же значение, которое было передано конструктору, или пустая ссылка, если <xref:System.Exception.InnerException%2A>свойства не предоставляет конструктору значение внутреннего исключения.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.ApplicationException>.</xref:System.ApplicationException>      |||   |-|-|   | Свойство | Значение |   | <xref:System.Exception.InnerException%2A>| `inner` Ссылки. |   | <xref:System.Exception.Message%2A>| `message` Строка. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "Объект <xref:System.String>объект, описывающий ошибку.</xref:System.String>"
    - id: inner
      type: System.Exception
      description: "<xref:System.Exception>Объекта, которое является причиной текущего исключения.</xref:System.Exception> Если <xref:System.Exception.InnerException*>параметр не является указателем null (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> в Visual Basic), текущее исключение сгенерировано в блоке catch, обрабатывающем внутреннее исключение.</xref:System.Exception.InnerException*>"
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException
  nameWithType: NoStartupFormException.NoStartupFormException
