### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  id: UnhandledExceptionEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  - Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  langs:
  - csharp
  name: UnhandledExceptionEventArgs
  nameWithType: UnhandledExceptionEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  type: Class
  summary: "Предоставляет данные для <xref uid=&quot;langword_csharp_My.Application.UnhandledException&quot; name=&quot;My.Application.UnhandledException&quot; href=&quot;&quot;> </xref> событий."
  remarks: "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException>Событие возникает при возникновении необработанного исключения в приложении, которое реализует модель приложения Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException> Дополнительные сведения см. в разделе [Обзор модели приложения Visual Basic](~/add/includes/ajax-current-ext-md.md).       Содержит UnhandledExceptionEventArgs <xref:System.Exception>, произошла и указывает, должно ли приложение завершать работу при выходе из обработчика исключений.</xref:System.Exception>"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class UnhandledExceptionEventArgs : System.Threading.ThreadExceptionEventArgs
  inheritance:
  - System.EventArgs
  - System.Threading.ThreadExceptionEventArgs
  implements: []
  inheritedMembers:
  - System.Threading.ThreadExceptionEventArgs.Exception
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  id: '#ctor(System.Boolean,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  langs:
  - csharp
  name: UnhandledExceptionEventArgs(Boolean,Exception)
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Инициализирует новый экземпляр <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs&quot;> </xref> класса."
  remarks: "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException>Событие возникает при возникновении необработанного исключения в приложении, которое реализует модель приложения Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException> Дополнительные сведения см. в разделе [Обзор модели приложения Visual Basic](~/add/includes/ajax-current-ext-md.md).       <xref:Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs>содержит <xref:System.Exception>, произошла и указывает, должно ли приложение завершать работу при выходе из обработчика исключений.</xref:System.Exception></xref:Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs>"
  syntax:
    content: public UnhandledExceptionEventArgs (bool exitApplication, Exception exception);
    parameters:
    - id: exitApplication
      type: System.Boolean
      description: "Объект <xref:System.Boolean>, указывающее, должно ли приложение завершать работу при выходе из обработчика исключений.</xref:System.Boolean>"
    - id: exception
      type: System.Exception
      description: "<xref:System.Exception>Возникшее.</xref:System.Exception>"
  overload: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  id: ExitApplication
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  langs:
  - csharp
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Указывает, должно ли приложение завершать работу при выходе из обработчика исключений."
  remarks: "Модель приложения Visual Basic проверяет значение этого свойства после выполнения обработчик <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException>событий.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException> Если ExitApplication `True`, а затем выхода из приложения. В противном случае приложение продолжает работать. Дополнительные сведения см. в разделе [Обзор модели приложения Visual Basic](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public bool ExitApplication { get; set; }
    return:
      type: System.Boolean
      description: "Объект <xref:System.Boolean>, указывающее, должно ли приложение завершать работу при выходе из обработчика исключений.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Threading.ThreadExceptionEventArgs
  isExternal: false
  name: System.Threading.ThreadExceptionEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: UnhandledExceptionEventArgs(Boolean,Exception)
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: UnhandledExceptionEventArgs
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication*
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
