### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  id: ManifestWriter
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.IO.Stream)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String,System.String)
  langs:
  - csharp
  name: ManifestWriter
  nameWithType: ManifestWriter
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  type: Class
  summary: "Записывает объектное представление манифеста в XML."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public static class ManifestWriter
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest)
  id: WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  langs:
  - csharp
  name: WriteManifest(Manifest)
  nameWithType: ManifestWriter.WriteManifest(Manifest)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Записывает заданный объект манифеста в XML."
  remarks: "Записывает заданное объектное представление манифеста в XML. Имя выходного файла выводится из <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.SourcePath%2A>Свойства манифеста.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.SourcePath%2A>"
  syntax:
    content: public static void WriteManifest (Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest manifest);
    parameters:
    - id: manifest
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: "Объект манифеста."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.IO.Stream)
  id: WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.IO.Stream)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  langs:
  - csharp
  name: WriteManifest(Manifest,Stream)
  nameWithType: ManifestWriter.WriteManifest(Manifest,Stream)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,Stream)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Записывает заданный объект манифеста в XML."
  remarks: "Записывает заданное объектное представление манифеста в XML."
  syntax:
    content: public static void WriteManifest (Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest manifest, System.IO.Stream output);
    parameters:
    - id: manifest
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: "Объект манифеста."
    - id: output
      type: System.IO.Stream
      description: "Указывает выходной поток."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String)
  id: WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  langs:
  - csharp
  name: WriteManifest(Manifest,String)
  nameWithType: ManifestWriter.WriteManifest(Manifest,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,String)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Записывает заданный объект манифеста в XML."
  remarks: "Записывает заданное объектное представление манифеста в XML."
  syntax:
    content: public static void WriteManifest (Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest manifest, string path);
    parameters:
    - id: manifest
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: "Объект манифеста."
    - id: path
      type: System.String
      description: "Имя пути к выходному файлу."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String,System.String)
  id: WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  langs:
  - csharp
  name: WriteManifest(Manifest,String,String)
  nameWithType: ManifestWriter.WriteManifest(Manifest,String,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,String,String)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Записывает заданный объект манифеста в XML."
  syntax:
    content: public static void WriteManifest (Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest manifest, string path, string targetframeWorkVersion);
    parameters:
    - id: manifest
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: "Объект манифеста."
    - id: path
      type: System.String
      description: "Имя пути к выходному файлу."
    - id: targetframeWorkVersion
      type: System.String
      description: "Требуемой версии .NET framework."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  isExternal: false
  name: WriteManifest(Manifest)
  nameWithType: ManifestWriter.WriteManifest(Manifest)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: Manifest
  nameWithType: Manifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.IO.Stream)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  isExternal: false
  name: WriteManifest(Manifest,Stream)
  nameWithType: ManifestWriter.WriteManifest(Manifest,Stream)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,Stream)
- uid: System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  isExternal: false
  name: WriteManifest(Manifest,String)
  nameWithType: ManifestWriter.WriteManifest(Manifest,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  isExternal: false
  name: WriteManifest(Manifest,String,String)
  nameWithType: ManifestWriter.WriteManifest(Manifest,String,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,String,String)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  isExternal: false
  name: WriteManifest
  nameWithType: ManifestWriter.WriteManifest
