### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  id: DownloadApplicationCompletedEventArgs
  children:
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  langs:
  - csharp
  name: DownloadApplicationCompletedEventArgs
  nameWithType: DownloadApplicationCompletedEventArgs
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  type: Class
  summary: "Предоставляет данные для <xref href=&quot;System.Deployment.Application.InPlaceHostingManager.DownloadApplicationCompleted&quot;> </xref> событий."
  syntax:
    content: 'public class DownloadApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  id: LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Возвращает путь к файлу журнала ClickOnce."
  syntax:
    content: public string LogFilePath { get; }
    return:
      type: System.String
      description: "Путь файла журнала ClickOnce."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  id: ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Получает содержимое файла APPREF ms, который можно запустить это приложение ClickOnce."
  remarks: 'Это свойство содержит текст пользовательского установщика можно записать в файл APPREF ms, чтобы запустить это приложение ClickOnce. ClickOnce создает этот файл запуска при установке приложения ClickOnce, которое доступно в автономном режиме, за исключением приложений, которые включают `<customUX>` элемента. Пользовательский установщик можно создать ярлык для запуска приложения ClickOnce, которое содержит `<customUX>` элемент путем написания текста в это свойство в файл APPREF ms в формате Юникод. Дополнительные сведения см. в разделе [ \&lt; entryPoint\&gt; Элемент](../Topic/%3CentryPoint%3E%20Element%20\(ClickOnce%20Application\).md) и [Пошаговое руководство: Создание пользовательского установщика для приложения ClickOnce](~/add/includes/ajax-current-ext-md.md).'
  syntax:
    content: public string ShortcutAppId { get; }
    return:
      type: System.String
      description: "Содержимое файла APPREF ms."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
