### YamlMime:ManagedReference
items:
- uid: System.DirectoryServices.DirectoryEntryConfiguration
  id: DirectoryEntryConfiguration
  children:
  - System.DirectoryServices.DirectoryEntryConfiguration.GetCurrentServerName
  - System.DirectoryServices.DirectoryEntryConfiguration.IsMutuallyAuthenticated
  - System.DirectoryServices.DirectoryEntryConfiguration.PageSize
  - System.DirectoryServices.DirectoryEntryConfiguration.PasswordEncoding
  - System.DirectoryServices.DirectoryEntryConfiguration.PasswordPort
  - System.DirectoryServices.DirectoryEntryConfiguration.Referral
  - System.DirectoryServices.DirectoryEntryConfiguration.SecurityMasks
  - System.DirectoryServices.DirectoryEntryConfiguration.SetUserNameQueryQuota(System.String)
  langs:
  - csharp
  name: DirectoryEntryConfiguration
  nameWithType: DirectoryEntryConfiguration
  fullName: System.DirectoryServices.DirectoryEntryConfiguration
  type: Class
  summary: "Класс DirectoryEntryConfiguration предоставляет простой способ указать и получать параметры поставщика для управления объектом каталога. Как правило параметры применяются для поиска операций в базовом хранилище каталога. Поддерживаемые параметры зависят от поставщика."
  syntax:
    content: public class DirectoryEntryConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.DirectoryServices.DirectoryEntryConfiguration.GetCurrentServerName
  id: GetCurrentServerName
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  langs:
  - csharp
  name: GetCurrentServerName()
  nameWithType: DirectoryEntryConfiguration.GetCurrentServerName()
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.GetCurrentServerName()
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices
  summary: "Возвращает имя узла сервера для текущей привязки к данному объекту каталога."
  syntax:
    content: public string GetCurrentServerName ();
    parameters: []
    return:
      type: System.String
      description: "Имя сервера."
  overload: System.DirectoryServices.DirectoryEntryConfiguration.GetCurrentServerName*
  exceptions: []
  platform:
  - net462
- uid: System.DirectoryServices.DirectoryEntryConfiguration.IsMutuallyAuthenticated
  id: IsMutuallyAuthenticated
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  langs:
  - csharp
  name: IsMutuallyAuthenticated()
  nameWithType: DirectoryEntryConfiguration.IsMutuallyAuthenticated()
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.IsMutuallyAuthenticated()
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices
  summary: "Определяет, если взаимная проверка подлинности выполняется на уровне SSPI."
  syntax:
    content: public bool IsMutuallyAuthenticated ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Если была выполнена взаимная проверка подлинности; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.DirectoryServices.DirectoryEntryConfiguration.IsMutuallyAuthenticated*
  exceptions: []
  platform:
  - net462
- uid: System.DirectoryServices.DirectoryEntryConfiguration.PageSize
  id: PageSize
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  langs:
  - csharp
  name: PageSize
  nameWithType: DirectoryEntryConfiguration.PageSize
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.PageSize
  type: Property
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices
  summary: "Возвращает или задает размер страницы при постраничном поиске."
  syntax:
    content: public int PageSize { get; set; }
    return:
      type: System.Int32
      description: "Количество записей на странице."
  overload: System.DirectoryServices.DirectoryEntryConfiguration.PageSize*
  exceptions: []
  platform:
  - net462
- uid: System.DirectoryServices.DirectoryEntryConfiguration.PasswordEncoding
  id: PasswordEncoding
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  langs:
  - csharp
  name: PasswordEncoding
  nameWithType: DirectoryEntryConfiguration.PasswordEncoding
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.PasswordEncoding
  type: Property
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices
  summary: "Возвращает или задает пароль, метод шифрования."
  syntax:
    content: public System.DirectoryServices.PasswordEncodingMethod PasswordEncoding { get; set; }
    return:
      type: System.DirectoryServices.PasswordEncodingMethod
      description: "Один из <xref href=&quot;System.DirectoryServices.PasswordEncodingMethod&quot;> </xref> членов перечисления, которое указывает тип кодировки пароль."
  overload: System.DirectoryServices.DirectoryEntryConfiguration.PasswordEncoding*
  exceptions: []
  platform:
  - net462
- uid: System.DirectoryServices.DirectoryEntryConfiguration.PasswordPort
  id: PasswordPort
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  langs:
  - csharp
  name: PasswordPort
  nameWithType: DirectoryEntryConfiguration.PasswordPort
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.PasswordPort
  type: Property
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices
  summary: "Возвращает или задает номер порта, который используется для установки SSL-соединения при установке или изменении пароля."
  remarks: "По умолчанию порт 636 используется для установки SSL-соединения при установке или изменении пароля."
  syntax:
    content: public int PasswordPort { get; set; }
    return:
      type: System.Int32
      description: "Номер порта, который должен использоваться для установки SSL-соединения при установке или изменении пароля."
  overload: System.DirectoryServices.DirectoryEntryConfiguration.PasswordPort*
  exceptions: []
  platform:
  - net462
- uid: System.DirectoryServices.DirectoryEntryConfiguration.Referral
  id: Referral
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  langs:
  - csharp
  name: Referral
  nameWithType: DirectoryEntryConfiguration.Referral
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.Referral
  type: Property
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices
  summary: "Возвращает или задает значение, определяющее, если и как рассмотреть прослеживании ссылок."
  syntax:
    content: public System.DirectoryServices.ReferralChasingOption Referral { get; set; }
    return:
      type: System.DirectoryServices.ReferralChasingOption
      description: "Сочетание одного или нескольких <xref href=&quot;System.DirectoryServices.ReferralChasingOption&quot;> </xref> членов перечисления, указывающее, если и как рассмотреть прослеживании ссылок."
  overload: System.DirectoryServices.DirectoryEntryConfiguration.Referral*
  exceptions: []
  platform:
  - net462
- uid: System.DirectoryServices.DirectoryEntryConfiguration.SecurityMasks
  id: SecurityMasks
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  langs:
  - csharp
  name: SecurityMasks
  nameWithType: DirectoryEntryConfiguration.SecurityMasks
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.SecurityMasks
  type: Property
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices
  summary: "Возвращает или задает маску безопасности для использования с <xref href=&quot;System.DirectoryServices.DirectoryEntryConfiguration&quot;> </xref>."
  syntax:
    content: public System.DirectoryServices.SecurityMasks SecurityMasks { get; set; }
    return:
      type: System.DirectoryServices.SecurityMasks
      description: "Сочетание одного или нескольких <xref href=&quot;System.DirectoryServices.SecurityMasks&quot;> </xref> членов перечисления, маска безопасности."
  overload: System.DirectoryServices.DirectoryEntryConfiguration.SecurityMasks*
  exceptions: []
  platform:
  - net462
- uid: System.DirectoryServices.DirectoryEntryConfiguration.SetUserNameQueryQuota(System.String)
  id: SetUserNameQueryQuota(System.String)
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  langs:
  - csharp
  name: SetUserNameQueryQuota(String)
  nameWithType: DirectoryEntryConfiguration.SetUserNameQueryQuota(String)
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.SetUserNameQueryQuota(String)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices
  summary: "Задает имя субъекта безопасности, чтобы при обращении к участнику, его квоты будут также возвращены сведения."
  syntax:
    content: public void SetUserNameQueryQuota (string accountName);
    parameters:
    - id: accountName
      type: System.String
      description: "Имя учетной записи, которое должно быть задано для обеспечения возможности запросов по его имени участника."
  overload: System.DirectoryServices.DirectoryEntryConfiguration.SetUserNameQueryQuota*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.DirectoryServices.DirectoryEntryConfiguration.GetCurrentServerName
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: GetCurrentServerName()
  nameWithType: DirectoryEntryConfiguration.GetCurrentServerName()
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.GetCurrentServerName()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.DirectoryServices.DirectoryEntryConfiguration.IsMutuallyAuthenticated
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: IsMutuallyAuthenticated()
  nameWithType: DirectoryEntryConfiguration.IsMutuallyAuthenticated()
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.IsMutuallyAuthenticated()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.DirectoryServices.DirectoryEntryConfiguration.PageSize
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: PageSize
  nameWithType: DirectoryEntryConfiguration.PageSize
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.PageSize
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.DirectoryServices.DirectoryEntryConfiguration.PasswordEncoding
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: PasswordEncoding
  nameWithType: DirectoryEntryConfiguration.PasswordEncoding
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.PasswordEncoding
- uid: System.DirectoryServices.PasswordEncodingMethod
  parent: System.DirectoryServices
  isExternal: false
  name: PasswordEncodingMethod
  nameWithType: PasswordEncodingMethod
  fullName: System.DirectoryServices.PasswordEncodingMethod
- uid: System.DirectoryServices.DirectoryEntryConfiguration.PasswordPort
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: PasswordPort
  nameWithType: DirectoryEntryConfiguration.PasswordPort
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.PasswordPort
- uid: System.DirectoryServices.DirectoryEntryConfiguration.Referral
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: Referral
  nameWithType: DirectoryEntryConfiguration.Referral
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.Referral
- uid: System.DirectoryServices.ReferralChasingOption
  parent: System.DirectoryServices
  isExternal: false
  name: ReferralChasingOption
  nameWithType: ReferralChasingOption
  fullName: System.DirectoryServices.ReferralChasingOption
- uid: System.DirectoryServices.DirectoryEntryConfiguration.SecurityMasks
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: SecurityMasks
  nameWithType: DirectoryEntryConfiguration.SecurityMasks
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.SecurityMasks
- uid: System.DirectoryServices.SecurityMasks
  parent: System.DirectoryServices
  isExternal: false
  name: SecurityMasks
  nameWithType: SecurityMasks
  fullName: System.DirectoryServices.SecurityMasks
- uid: System.DirectoryServices.DirectoryEntryConfiguration.SetUserNameQueryQuota(System.String)
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: SetUserNameQueryQuota(String)
  nameWithType: DirectoryEntryConfiguration.SetUserNameQueryQuota(String)
  fullName: System.DirectoryServices.DirectoryEntryConfiguration.SetUserNameQueryQuota(String)
- uid: System.DirectoryServices.DirectoryEntryConfiguration.GetCurrentServerName*
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: GetCurrentServerName
  nameWithType: DirectoryEntryConfiguration.GetCurrentServerName
- uid: System.DirectoryServices.DirectoryEntryConfiguration.IsMutuallyAuthenticated*
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: IsMutuallyAuthenticated
  nameWithType: DirectoryEntryConfiguration.IsMutuallyAuthenticated
- uid: System.DirectoryServices.DirectoryEntryConfiguration.PageSize*
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: PageSize
  nameWithType: DirectoryEntryConfiguration.PageSize
- uid: System.DirectoryServices.DirectoryEntryConfiguration.PasswordEncoding*
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: PasswordEncoding
  nameWithType: DirectoryEntryConfiguration.PasswordEncoding
- uid: System.DirectoryServices.DirectoryEntryConfiguration.PasswordPort*
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: PasswordPort
  nameWithType: DirectoryEntryConfiguration.PasswordPort
- uid: System.DirectoryServices.DirectoryEntryConfiguration.Referral*
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: Referral
  nameWithType: DirectoryEntryConfiguration.Referral
- uid: System.DirectoryServices.DirectoryEntryConfiguration.SecurityMasks*
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: SecurityMasks
  nameWithType: DirectoryEntryConfiguration.SecurityMasks
- uid: System.DirectoryServices.DirectoryEntryConfiguration.SetUserNameQueryQuota*
  parent: System.DirectoryServices.DirectoryEntryConfiguration
  isExternal: false
  name: SetUserNameQueryQuota
  nameWithType: DirectoryEntryConfiguration.SetUserNameQueryQuota
