### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyValidation
  id: MachineKeyValidation
  children:
  - System.Web.Configuration.MachineKeyValidation.AES
  - System.Web.Configuration.MachineKeyValidation.Custom
  - System.Web.Configuration.MachineKeyValidation.HMACSHA256
  - System.Web.Configuration.MachineKeyValidation.HMACSHA384
  - System.Web.Configuration.MachineKeyValidation.HMACSHA512
  - System.Web.Configuration.MachineKeyValidation.MD5
  - System.Web.Configuration.MachineKeyValidation.SHA1
  - System.Web.Configuration.MachineKeyValidation.TripleDES
  langs:
  - csharp
  name: MachineKeyValidation
  nameWithType: MachineKeyValidation
  fullName: System.Web.Configuration.MachineKeyValidation
  type: Enum
  summary: "Задает алгоритм хэширования, используемого ASP.NET для проверки подлинности форм и проверки данных состояния представления и для идентификации состояния сеанса вне процесса."
  remarks: "ASP.NET использует кода подлинности сообщения на основе хэша (HMAC) для обнаружения подделки данных, используемый для проверки подлинности или представление состояния формы с. HMAC формируется при создании представления состояния содержимого и HMAC проверяется при последующих запросах. HMAC помогает определить, является ли изменения данных, передаваемых между сервером и клиентом, но данные могут быть прочитаны никем другим, как он проходит через Интернет, если он зашифрован также ASP.NET. По умолчанию состояние представления проверены, но не шифруются. Дополнительные сведения см. в разделе <xref:System.Web.UI.Page.ViewStateEncryptionMode%2A>и <xref:System.Web.UI.Page.RegisterRequiresViewStateEncryption%2A>.</xref:System.Web.UI.Page.RegisterRequiresViewStateEncryption%2A> </xref:System.Web.UI.Page.ViewStateEncryptionMode%2A>       Перечисление MachineKeyValidation позволяет указать алгоритм, используемый для создания кода HMAC ASP.NET. Значение по умолчанию — HMACSHA256. ASP.NET использует значение <xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>Свойства с выбранным алгоритмом для создания кода HMAC.</xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>"
  example:
  - "The following code example shows how to use the MachineKeyValidation enumeration. In the example, `configSection` is an instance of <xref:System.Web.Configuration.MachineKeySection>.This code example is part of a larger example provided for the <xref:System.Web.Configuration.MachineKeySection> class.  \n  \n [!code-vb[System.Web.Configuration.MachineKeySection#5](~/add/codesnippet/visualbasic/t-system.web.configurati_93_1.vb)]\n [!code-cs[System.Web.Configuration.MachineKeySection#5](~/add/codesnippet/csharp/t-system.web.configurati_93_1.cs)]"
  syntax:
    content: public enum MachineKeyValidation
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.AES
  id: AES
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: AES
  nameWithType: MachineKeyValidation.AES
  fullName: System.Web.Configuration.MachineKeyValidation.AES
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что ASP.NET использует <xref uid=&quot;langword_csharp_AES&quot; name=&quot;AES&quot; href=&quot;&quot;> </xref> алгоритма шифрования (Rijndael)."
  remarks: "Выберите этот параметр, если требуется шифровать состояние просмотра в веб-приложении. При выборе этого параметра <xref:System.Web.Configuration.MachineKeySection.DecryptionKey%2A>свойство будет использоваться для шифрования и расшифровки и `HMACSHA1` хэш-алгоритма, которые будут использоваться с <xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>свойство для проверки.</xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A> </xref:System.Web.Configuration.MachineKeySection.DecryptionKey%2A>"
  syntax:
    content: AES
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.Custom
  id: Custom
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: Custom
  nameWithType: MachineKeyValidation.Custom
  fullName: System.Web.Configuration.MachineKeyValidation.Custom
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что ASP.NET использует пользовательский алгоритм хэширования."
  remarks: "Пользовательский алгоритм хэширования, которые могут быть реализованы в любой класс, производный от <xref:System.Security.Cryptography.KeyedHashAlgorithm>.</xref:System.Security.Cryptography.KeyedHashAlgorithm>       Пользовательский алгоритм обычно задается декларативно в атрибут проверки элемента в формате `alg:` *algorithm_name*. Сведения об указании пользовательского алгоритма в коде см. в разделе <xref:System.Web.Configuration.MachineKeySection.ValidationAlgorithm%2A?displayProperty=fullName>свойство.</xref:System.Web.Configuration.MachineKeySection.ValidationAlgorithm%2A?displayProperty=fullName>"
  syntax:
    content: Custom
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  id: HMACSHA256
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA256
  nameWithType: MachineKeyValidation.HMACSHA256
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что ASP.NET использует <xref uid=&quot;langword_csharp_HMACSHA256&quot; name=&quot;HMACSHA256&quot; href=&quot;&quot;> </xref> хэш-алгоритм.  Это значение по умолчанию."
  remarks: '`HMACSHA256`является SHA2 алгоритм хэширования, который создает 256-разрядный хэш-код.'
  syntax:
    content: HMACSHA256
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  id: HMACSHA384
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA384
  nameWithType: MachineKeyValidation.HMACSHA384
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что ASP.NET использует <xref uid=&quot;langword_csharp_HMACSHA384&quot; name=&quot;HMACSHA384&quot; href=&quot;&quot;> </xref> хэш-алгоритм."
  remarks: '`HMACSHA384`является SHA2 алгоритм хэширования, который приводит к возникновению ошибки 384-разрядный хэш-код. Этот параметр доступен для приложений, требующих более высокий уровень безопасности, чем в `HMACSHA256`алгоритма.'
  syntax:
    content: HMACSHA384
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  id: HMACSHA512
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA512
  nameWithType: MachineKeyValidation.HMACSHA512
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что ASP.NET использует <xref uid=&quot;langword_csharp_HMACSHA512&quot; name=&quot;HMACSHA512&quot; href=&quot;&quot;> </xref> хэш-алгоритм."
  remarks: '`HMACSHA512`является SHA2 алгоритм хэширования, который приводит к возникновению ошибки 512-разрядный хэш-код. Этот параметр доступен для приложений, требующих более высокий уровень безопасности, чем в `HMACSHA384` алгоритма.'
  syntax:
    content: HMACSHA512
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.MD5
  id: MD5
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: MD5
  nameWithType: MachineKeyValidation.MD5
  fullName: System.Web.Configuration.MachineKeyValidation.MD5
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что ASP.NET использует Message Digest 5 (<xref uid=&quot;langword_csharp_MD5&quot; name=&quot;MD5&quot; href=&quot;&quot;></xref>) хэш-алгоритм."
  remarks: '`MD5`представляет алгоритм хэширования, который создает 128-разрядный хэш-значение. Этот параметр включен для обратной совместимости и должен быть установлен только в том случае, если требуется совместимость с предыдущими версиями ASP.NET.'
  syntax:
    content: MD5
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.SHA1
  id: SHA1
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: SHA1
  nameWithType: MachineKeyValidation.SHA1
  fullName: System.Web.Configuration.MachineKeyValidation.SHA1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что ASP.NET использует <xref uid=&quot;langword_csharp_HMACSHA1&quot; name=&quot;HMACSHA1&quot; href=&quot;&quot;> </xref> хэш-алгоритм."
  remarks: '`HMACSHA1`представляет алгоритм хэширования, который формирует 160-разрядный хэш-значение. Этот параметр включен для обратной совместимости и должен быть установлен только в том случае, если требуется совместимость с предыдущими версиями ASP.NET.'
  syntax:
    content: SHA1
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.TripleDES
  id: TripleDES
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: TripleDES
  nameWithType: MachineKeyValidation.TripleDES
  fullName: System.Web.Configuration.MachineKeyValidation.TripleDES
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что ASP.NET использует TripleDES (<xref uid=&quot;langword_csharp_3DES&quot; name=&quot;3DES&quot; href=&quot;&quot;></xref>) алгоритм шифрования."
  remarks: "TripleDES — это алгоритм шифрования, который используется только в том случае, если указать шифровании состояния просмотра. Этот параметр включен для обратной совместимости и должен быть установлен только в том случае, если требуется совместимость с предыдущими версиями ASP.NET."
  syntax:
    content: TripleDES
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyValidation.AES
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: AES
  nameWithType: MachineKeyValidation.AES
  fullName: System.Web.Configuration.MachineKeyValidation.AES
- uid: System.Web.Configuration.MachineKeyValidation
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyValidation
  nameWithType: MachineKeyValidation
  fullName: System.Web.Configuration.MachineKeyValidation
- uid: System.Web.Configuration.MachineKeyValidation.Custom
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: Custom
  nameWithType: MachineKeyValidation.Custom
  fullName: System.Web.Configuration.MachineKeyValidation.Custom
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA256
  nameWithType: MachineKeyValidation.HMACSHA256
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA256
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA384
  nameWithType: MachineKeyValidation.HMACSHA384
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA384
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA512
  nameWithType: MachineKeyValidation.HMACSHA512
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA512
- uid: System.Web.Configuration.MachineKeyValidation.MD5
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: MD5
  nameWithType: MachineKeyValidation.MD5
  fullName: System.Web.Configuration.MachineKeyValidation.MD5
- uid: System.Web.Configuration.MachineKeyValidation.SHA1
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: SHA1
  nameWithType: MachineKeyValidation.SHA1
  fullName: System.Web.Configuration.MachineKeyValidation.SHA1
- uid: System.Web.Configuration.MachineKeyValidation.TripleDES
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: TripleDES
  nameWithType: MachineKeyValidation.TripleDES
  fullName: System.Web.Configuration.MachineKeyValidation.TripleDES
