### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFrameworks
  id: CompatibleFrameworks
  children:
  - System.Deployment.Application.CompatibleFrameworks.Frameworks
  - System.Deployment.Application.CompatibleFrameworks.SupportUrl
  langs:
  - csharp
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworks
  type: Class
  summary: "Предоставляет сведения о версии платформы .NET Framework, на котором можно установить и запустить это приложение."
  syntax:
    content: public class CompatibleFrameworks
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworks.Frameworks
  id: Frameworks
  parent: System.Deployment.Application.CompatibleFrameworks
  langs:
  - csharp
  name: Frameworks
  nameWithType: CompatibleFrameworks.Frameworks
  fullName: System.Deployment.Application.CompatibleFrameworks.Frameworks
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Получает список версий .NET Framework, на которых можно установить и запустить это приложение."
  syntax:
    content: public System.Collections.Generic.IList<System.Deployment.Application.CompatibleFramework> Frameworks { get; }
    return:
      type: System.Collections.Generic.IList{System.Deployment.Application.CompatibleFramework}
      description: "Список <xref href=&quot;System.Deployment.Application.CompatibleFramework&quot;> </xref> объектов, которые задают версий .NET Framework, на которых можно установить и запустить это приложение."
  overload: System.Deployment.Application.CompatibleFrameworks.Frameworks*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworks.SupportUrl
  id: SupportUrl
  parent: System.Deployment.Application.CompatibleFrameworks
  langs:
  - csharp
  name: SupportUrl
  nameWithType: CompatibleFrameworks.SupportUrl
  fullName: System.Deployment.Application.CompatibleFrameworks.SupportUrl
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Возвращает <xref:System.Uri>, предоставляющий пользователю с инструкциями по установке версии платформы .NET Framework, на котором можно установить и запустить это приложение.</xref:System.Uri>"
  remarks: "Свойство SupportUrl содержит <xref:System.Uri>, которые могут возникнуть в `SupportUrl` атрибута в [ \\&lt; compatibleFrameworks\\&gt; Элемент](../Topic/%3CcompatibleFrameworks%3E%20Element%20\\(ClickOnce%20Deployment\\).md).</xref:System.Uri>"
  syntax:
    content: public Uri SupportUrl { get; }
    return:
      type: System.Uri
      description: "Объект <xref:System.Uri>, предоставляющий пользователю с инструкциями по установке версии платформы .NET Framework, на котором можно установить и запустить это приложение.</xref:System.Uri>"
  overload: System.Deployment.Application.CompatibleFrameworks.SupportUrl*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Application.CompatibleFrameworks.Frameworks
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: Frameworks
  nameWithType: CompatibleFrameworks.Frameworks
  fullName: System.Deployment.Application.CompatibleFrameworks.Frameworks
- uid: System.Collections.Generic.IList{System.Deployment.Application.CompatibleFramework}
  parent: System.Collections.Generic
  isExternal: true
  name: IList<CompatibleFramework>
  nameWithType: IList<CompatibleFramework>
  fullName: System.Collections.Generic.IList<System.Deployment.Application.CompatibleFramework>
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: IList<System.Deployment.Application.CompatibleFramework>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Deployment.Application.CompatibleFramework
    name: CompatibleFramework
    nameWithType: CompatibleFramework
    fullName: CompatibleFramework
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Deployment.Application.CompatibleFrameworks.SupportUrl
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: SupportUrl
  nameWithType: CompatibleFrameworks.SupportUrl
  fullName: System.Deployment.Application.CompatibleFrameworks.SupportUrl
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Deployment.Application.CompatibleFrameworks.Frameworks*
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: Frameworks
  nameWithType: CompatibleFrameworks.Frameworks
- uid: System.Deployment.Application.CompatibleFrameworks.SupportUrl*
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: SupportUrl
  nameWithType: CompatibleFrameworks.SupportUrl
