### YamlMime:ManagedReference
items:
- uid: System.Windows.Forms.LayoutSettings
  id: LayoutSettings
  children:
  - System.Windows.Forms.LayoutSettings.#ctor
  - System.Windows.Forms.LayoutSettings.LayoutEngine
  langs:
  - csharp
  name: LayoutSettings
  nameWithType: LayoutSettings
  fullName: System.Windows.Forms.LayoutSettings
  type: Class
  summary: "Предоставляет базовый класс для сбора характеристики схемы структуры."
  remarks: "Класс LayoutSettings является базовым классом для типов, которые собирают различные характеристики являются общими для схемы макета пользовательского интерфейса конкретного пользователя, например <xref:System.Windows.Forms.TableLayoutSettings>и <xref:System.Windows.Forms.FlowLayoutSettings>.</xref:System.Windows.Forms.FlowLayoutSettings> </xref:System.Windows.Forms.TableLayoutSettings>"
  example:
  - "The following example shows how to initialize a <xref:System.Windows.Forms.TableLayoutSettings> object for a <xref:System.Windows.Forms.TableLayoutPanel> control. For a full code listing, see [How to: Implement a Custom ToolStripRenderer](~/add/includes/ajax-current-ext-md.md).  \n  \n [!code-vb[System.Windows.Forms.ToolStrip.GridStrip#2](~/add/codesnippet/visualbasic/t-system.windows.forms.l_8_1.vb)]\n [!code-cs[System.Windows.Forms.ToolStrip.GridStrip#2](~/add/codesnippet/csharp/t-system.windows.forms.l_8_1.cs)]"
  syntax:
    content: public abstract class LayoutSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Forms.LayoutSettings.#ctor
  id: '#ctor'
  parent: System.Windows.Forms.LayoutSettings
  langs:
  - csharp
  name: LayoutSettings()
  nameWithType: LayoutSettings.LayoutSettings()
  fullName: System.Windows.Forms.LayoutSettings.LayoutSettings()
  type: Constructor
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Windows.Forms.LayoutSettings&quot;> </xref> класса."
  syntax:
    content: protected LayoutSettings ();
    parameters: []
  overload: System.Windows.Forms.LayoutSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.LayoutSettings.LayoutEngine
  id: LayoutEngine
  parent: System.Windows.Forms.LayoutSettings
  langs:
  - csharp
  name: LayoutEngine
  nameWithType: LayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.LayoutSettings.LayoutEngine
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Возвращает текущий обработчик макета таблицы."
  remarks: '<xref:System.Windows.Forms.TableLayoutSettings.LayoutEngine%2A>Свойство обычно используется в двух контекстах: контейнер, использующий схему макета и дочерний элемент управления контейнера, к которому применяется макет схемы.</xref:System.Windows.Forms.TableLayoutSettings.LayoutEngine%2A>'
  syntax:
    content: public virtual System.Windows.Forms.Layout.LayoutEngine LayoutEngine { get; }
    return:
      type: System.Windows.Forms.Layout.LayoutEngine
      description: "<xref href=&quot;System.Windows.Forms.Layout.LayoutEngine&quot;> </xref> В настоящее время используется."
  overload: System.Windows.Forms.LayoutSettings.LayoutEngine*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Windows.Forms.LayoutSettings.#ctor
  parent: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: LayoutSettings()
  nameWithType: LayoutSettings.LayoutSettings()
  fullName: System.Windows.Forms.LayoutSettings.LayoutSettings()
- uid: System.Windows.Forms.LayoutSettings.LayoutEngine
  parent: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: LayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.LayoutSettings.LayoutEngine
- uid: System.Windows.Forms.Layout.LayoutEngine
  parent: System.Windows.Forms.Layout
  isExternal: false
  name: LayoutEngine
  nameWithType: LayoutEngine
  fullName: System.Windows.Forms.Layout.LayoutEngine
- uid: System.Windows.Forms.LayoutSettings.#ctor*
  parent: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: LayoutSettings
  nameWithType: LayoutSettings.LayoutSettings
- uid: System.Windows.Forms.LayoutSettings.LayoutEngine*
  parent: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: LayoutSettings.LayoutEngine
