### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationElementCollectionType
  id: ConfigurationElementCollectionType
  children:
  - System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  - System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  - System.Configuration.ConfigurationElementCollectionType.BasicMap
  - System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  langs:
  - csharp
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
  type: Enum
  summary: "Указывает тип объекта ConfigurationElementCollectionType."
  remarks: "Это перечисление содержит все возможные возвращаемые значения для <xref:System.Configuration.ConfigurationElementCollection.CollectionType%2A>свойство.</xref:System.Configuration.ConfigurationElementCollection.CollectionType%2A> Он используется системой конфигурации во время выполнения для корректного объединения установок конфигурации. Он также используется при создании пользовательского класса, расширяющий <xref:System.Configuration.ConfigurationElementCollection>.</xref:System.Configuration.ConfigurationElementCollection>       По умолчанию тип <xref:System.Configuration.ConfigurationElementCollection>объект является AddRemoveClearMap.</xref:System.Configuration.ConfigurationElementCollection> При необходимости BasicMap, переопределите это свойство ConfigurationElementCollectionType при расширении <xref:System.Configuration.ConfigurationElementCollection>.</xref:System.Configuration.ConfigurationElementCollection>"
  syntax:
    content: public enum ConfigurationElementCollectionType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  id: AddRemoveClearMap
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: AddRemoveClearMap
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMap
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Тип по умолчанию <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref>. Коллекции этого типа содержат элементы, которые могут объединяться в масштабе иерархии файлов конфигурации. На любом уровне такой иерархии <xref uid=&quot;langword_csharp_add&quot; name=&quot;add&quot; href=&quot;&quot;> </xref>, <xref uid=&quot;langword_csharp_remove&quot; name=&quot;remove&quot; href=&quot;&quot;> </xref>, и <xref uid=&quot;langword_csharp_clear&quot; name=&quot;clear&quot; href=&quot;&quot;> </xref> директивы используются для изменения любых унаследованных свойств и добавить новые."
  syntax:
    content: AddRemoveClearMap
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  id: AddRemoveClearMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: AddRemoveClearMapAlternate
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "То же, что AddRemoveClearMap, за исключением того, что этот тип вызывает <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref> объекта, чтобы отсортировать его содержимое таким образом, чтобы наследуемые элементы отображаются в последней."
  syntax:
    content: AddRemoveClearMapAlternate
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMap
  id: BasicMap
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: BasicMap
  nameWithType: ConfigurationElementCollectionType.BasicMap
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMap
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Коллекции этого типа содержат элементы, которые применяются к уровень, на котором они определены и на всех дочерних уровнях. Дочерний уровень не может изменить свойства, определенные родительским элементом данного типа."
  syntax:
    content: BasicMap
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  id: BasicMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: BasicMapAlternate
  nameWithType: ConfigurationElementCollectionType.BasicMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "То же, что BasicMap, за исключением того, что этот тип вызывает <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref> объекта, чтобы отсортировать его содержимое таким образом, чтобы наследуемые элементы отображаются в последней."
  syntax:
    content: BasicMapAlternate
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: AddRemoveClearMap
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMap
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
- uid: System.Configuration.ConfigurationElementCollectionType
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: AddRemoveClearMapAlternate
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMap
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: BasicMap
  nameWithType: ConfigurationElementCollectionType.BasicMap
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMap
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: BasicMapAlternate
  nameWithType: ConfigurationElementCollectionType.BasicMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
