### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IConfigMapPathFactory
  id: IConfigMapPathFactory
  children:
  - System.Web.Configuration.IConfigMapPathFactory.Create(System.String,System.String)
  langs:
  - csharp
  name: IConfigMapPathFactory
  nameWithType: IConfigMapPathFactory
  fullName: System.Web.Configuration.IConfigMapPathFactory
  type: Interface
  summary: "Сопоставляет пути к виртуальным и физическим файлам конфигурации."
  remarks: "IConfigMapPathFactory впервые появился в платформе .NET Framework версии 3.5.  Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public interface IConfigMapPathFactory
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPathFactory.Create(System.String,System.String)
  id: Create(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPathFactory
  langs:
  - csharp
  name: Create(String,String)
  nameWithType: IConfigMapPathFactory.Create(String,String)
  fullName: System.Web.Configuration.IConfigMapPathFactory.Create(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Создает интерфейс для сопоставления между виртуальными и физическими пути файла конфигурации."
  remarks: "Создание появился в платформе .NET Framework версии 3.5.  Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public System.Web.Configuration.IConfigMapPath Create (string virtualPath, string physicalPath);
    parameters:
    - id: virtualPath
      type: System.String
      description: "Виртуальный путь файла конфигурации."
    - id: physicalPath
      type: System.String
      description: "Физический путь файла конфигурации."
    return:
      type: System.Web.Configuration.IConfigMapPath
      description: "<xref href=&quot;System.Web.Configuration.IConfigMapPath&quot;> </xref> Объекта, связанного с сопоставлением путь указанного файла конфигурации."
  overload: System.Web.Configuration.IConfigMapPathFactory.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.IConfigMapPathFactory.Create(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPathFactory
  isExternal: false
  name: Create(String,String)
  nameWithType: IConfigMapPathFactory.Create(String,String)
  fullName: System.Web.Configuration.IConfigMapPathFactory.Create(String,String)
- uid: System.Web.Configuration.IConfigMapPath
  parent: System.Web.Configuration
  isExternal: false
  name: IConfigMapPath
  nameWithType: IConfigMapPath
  fullName: System.Web.Configuration.IConfigMapPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.IConfigMapPathFactory.Create*
  parent: System.Web.Configuration.IConfigMapPathFactory
  isExternal: false
  name: Create
  nameWithType: IConfigMapPathFactory.Create
