### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSettingAttribute
  id: SpecialSettingAttribute
  children:
  - System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  - System.Configuration.SpecialSettingAttribute.SpecialSetting
  langs:
  - csharp
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute
  fullName: System.Configuration.SpecialSettingAttribute
  type: Class
  summary: "Указывает, что свойство параметров приложения имеет специальное значение. Этот класс не наследуется."
  remarks: "Некоторые свойства параметров приложения имеют специальное значение, которое изменяет порядок, в котором соответствующим поставщиком параметров их обработки. SpecialSettingAttribute используется для определения таких свойств. Этот класс использует <xref:System.Configuration.SpecialSetting?displayProperty=fullName>перечисления, чтобы указать, какие специальные категории, свойство считается принадлежащим.</xref:System.Configuration.SpecialSetting?displayProperty=fullName>       SpecialSettingAttribute может применяться только для класса параметров или свойства отдельных параметров.       Пример, как поставщик параметров имеет дело с SpecialSettingAttribute в разделе <xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>метод <xref:System.Configuration.LocalFileSettingsProvider>класса.</xref:System.Configuration.LocalFileSettingsProvider> </xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SpecialSettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  id: '#ctor(System.Configuration.SpecialSetting)'
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Configuration.SpecialSettingAttribute&quot;> </xref> класса."
  syntax:
    content: public SpecialSettingAttribute (System.Configuration.SpecialSetting specialSetting);
    parameters:
    - id: specialSetting
      type: System.Configuration.SpecialSetting
      description: "Объект <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> значение перечисления, определяющее категорию свойства параметров приложения."
  overload: System.Configuration.SpecialSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  id: SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Возвращает значение, описывающее специальную категорию свойства параметров приложения."
  remarks: "Свойство SpecialSetting задается в <xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>конструктор этого класса.</xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SpecialSetting SpecialSetting { get; }
    return:
      type: System.Configuration.SpecialSetting
      description: "Объект <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> значение перечисления, определяющее категорию свойства параметров приложения."
  overload: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.#ctor*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
