### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  id: XmlFormatExtensionPointAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  type: Class
  summary: "Задает пространство имен XML и префикс пространства имен XML для расширения формата описания службы в описании службы. Этот класс не наследуется."
  remarks: "Расширение формата описания службы расширяет созданием описание службы для веб-служб XML с помощью ASP.NET. В частности расширение формата описания службы добавляет XML-элементы в описание службы. Это полезно в тех случаях, когда расширение SOAP создано для запуска на стороне клиента и сервера веб-служб XML, как сведения о расширениях SOAP не размещаются автоматически в описании службы. При добавлении сведений о расширении SOAP в описание службы клиент может интерпретировать необходимость запуска определенного расширения SOAP. Примером расширения SOAP, которое необходимо запустить на клиенте и сервере, является расширение SOAP для шифрования. Если расширение SOAP для шифрования выполняется только на сервере, и оно зашифровывает значения перед их отправкой обратно клиенту, клиент должен иметь запущено расширение SOAP для расшифровки сообщения SOAP. В противном случае клиент не может обработать возвращаемое значение.       Выполните следующие шаги для построения расширения формата описания службы: 1.  Создание класса, производного от <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>      2.  Применить <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>к классу и задайте точки расширения, в которых следует выполнить расширение формата описания службы.</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  При необходимости примените к классу XmlFormatExtensionPointAttribute и указания члена класса в качестве новой точки расширения.      4.  При необходимости примените <xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>к классу и укажите префикс пространства имен XML должен быть связан с XML-элементы, созданные с помощью расширения формата описания службы.</xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>      5.  Настройте расширение формата описания службы для запуска в составе `serviceDescriptionFormatExtensionTypes` раздел файла конфигурации."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_1_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_1_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class XmlFormatExtensionPointAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPointAttribute&quot;> </xref> класса."
  syntax:
    content: public XmlFormatExtensionPointAttribute (string memberName);
    parameters:
    - id: memberName
      type: System.String
      description: "Член класса, реализующего расширение формата описания службы, которые могут иметь расширение формата описания службы, связанные с ним."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  id: AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Возвращает или задает значение, которое показывает, определен ли член класса, реализующий расширение формата описания службы в <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>свойство можно использовать исходные элементы XML.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>"
  syntax:
    content: public bool AllowElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Если член класса, реализующего описания службы формат модуля, указанного в <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>свойство можно использовать исходные элементы XML; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*> Значение по умолчанию — <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  id: MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Указывает, что член класса, реализующий расширение формата описания службы, может иметь расширение формата описания службы, связанные с ним."
  syntax:
    content: public string MemberName { get; set; }
    return:
      type: System.String
      description: "Член класса, реализующего расширение формата описания службы, которые могут иметь расширение формата описания службы, связанные с ним."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
