### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventHandler
  id: DownloadFileGroupCompletedEventHandler
  langs:
  - csharp
  name: DownloadFileGroupCompletedEventHandler
  nameWithType: DownloadFileGroupCompletedEventHandler
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventHandler
  type: Delegate
  summary: "Представляет метод, обрабатывающий <xref href=&quot;System.Deployment.Application.ApplicationDeployment.DownloadFileGroupCompleted&quot;> </xref> событие <xref href=&quot;System.Deployment.Application.ApplicationDeployment&quot;> </xref>."
  remarks: 'При создании делегата DownloadFileGroupCompletedEventHandler необходимо указать метод, обрабатывающий событие. Чтобы связать событие с обработчиком событий, добавьте в событие экземпляр делегата. Обработчик событий вызывается всякий раз, когда происходит событие, пока не будет удален делегат. Дополнительные сведения о делегатах-обработчиках событий см. в разделе [NIB: события и делегаты](http://msdn.microsoft.com/en-us/d98fd58b-fa4f-4598-8378-addf4355a115).'
  syntax:
    content: public delegate void DownloadFileGroupCompletedEventHandler(object sender, DownloadFileGroupCompletedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
