### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.WorkflowEnvironment
  id: WorkflowEnvironment
  children:
  - System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  - System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  langs:
  - csharp
  name: WorkflowEnvironment
  nameWithType: WorkflowEnvironment
  fullName: System.Workflow.Runtime.WorkflowEnvironment
  type: Class
  summary: "Представляет среду выполнения транзакций экземпляра рабочего процесса, который выполняется в текущем потоке."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]WorkflowEnvironment представляет среду выполнения транзакций экземпляра рабочего процесса, который выполняется в текущем потоке. WorkflowEnvironment имеет два свойства: <xref:System.Workflow.Runtime.WorkflowEnvironment.WorkBatch%2A>свойство, которое показывает текущий пакет работ и позволяет узлу или службе узла участвовать в текущей транзакции, добавляя <xref:System.Workflow.Runtime.IPendingWork>элементов, это свойство; и <xref:System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId%2A>Свойства, которое предоставляет <xref:System.Guid>экземпляра рабочего процесса, выполняющегося в данный момент в этом потоке.</xref:System.Guid> </xref:System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId%2A> </xref:System.Workflow.Runtime.IPendingWork> </xref:System.Workflow.Runtime.WorkflowEnvironment.WorkBatch%2A>"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public static class WorkflowEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  id: WorkBatch
  parent: System.Workflow.Runtime.WorkflowEnvironment
  langs:
  - csharp
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "Возвращает текущий пакет работ."
  remarks: "Свойство пакета WorkBatch позволяет узлам или службам узлов участвовать в текущей транзакции, добавляя ожидающие работы в текущий пакет работ. Узел или служба узла, в которой необходимо участвовать в текущей транзакции должны реализовывать <xref:System.Workflow.Runtime.IPendingWork>интерфейса и использовать <xref:System.Workflow.Runtime.IWorkBatch.Add%2A?displayProperty=fullName>для добавления ожидающих работ для пакета WorkBatch.</xref:System.Workflow.Runtime.IWorkBatch.Add%2A?displayProperty=fullName> </xref:System.Workflow.Runtime.IPendingWork> Постоянные службы должны добавлять элементы для пакета WorkBatch, чтобы поддерживать состояние своих хранилищ данных, согласованные с состоянием экземпляра рабочего процесса. Out-of-box устойчивых служб, а также <xref:System.Workflow.Runtime.Tracking.SqlTrackingService>и <xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService>, как реализовать эту функцию.</xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService> </xref:System.Workflow.Runtime.Tracking.SqlTrackingService>"
  syntax:
    content: public static System.Workflow.Runtime.IWorkBatch WorkBatch { get; }
    return:
      type: System.Workflow.Runtime.IWorkBatch
      description: "<xref href=&quot;System.Workflow.Runtime.IWorkBatch&quot;> </xref> , Представляющий текущий пакет работ."
  overload: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  id: WorkflowInstanceId
  parent: System.Workflow.Runtime.WorkflowEnvironment
  langs:
  - csharp
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "Возвращает <xref:System.Guid>экземпляра рабочего процесса, связанного с текущим потоком.</xref:System.Guid>"
  remarks: "Содержит WorkflowInstanceId <xref:System.Guid>экземпляра рабочего процесса, выполняемых в этом потоке.</xref:System.Guid> Когда код запускается из потока рабочего процесса, можно получить <xref:System.Guid>экземпляра рабочего процесса через свойство WorkflowInstanceId.</xref:System.Guid> Например, если код находится в службе, вызванной действием, WorkflowInstanceId предоставляет <xref:System.Guid>экземпляра рабочего процесса для вызывающего действия.</xref:System.Guid>"
  syntax:
    content: public static Guid WorkflowInstanceId { get; }
    return:
      type: System.Guid
      description: "<xref:System.Guid>Определяет текущий экземпляр рабочего процесса.</xref:System.Guid>"
  overload: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
- uid: System.Workflow.Runtime.IWorkBatch
  parent: System.Workflow.Runtime
  isExternal: false
  name: IWorkBatch
  nameWithType: IWorkBatch
  fullName: System.Workflow.Runtime.IWorkBatch
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch*
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId*
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
