### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.IServerWebConfig
  id: IServerWebConfig
  children:
  - System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: IServerWebConfig
  nameWithType: IServerWebConfig
  fullName: System.EnterpriseServices.Internal.IServerWebConfig
  type: Interface
  summary: "Создает файл Web.config для приложения COM + с поддержкой протокола SOAP и добавляет компонент записи в файл для COM-интерфейсов, публикуемых в приложение."
  remarks: "Только путем реализации интерфейса IServerWebConfig <xref:System.EnterpriseServices.Internal.ServerWebConfig>класса и используется только в платформу .NET Framework.</xref:System.EnterpriseServices.Internal.ServerWebConfig> Вместо реализации этого интерфейса или создания экземпляра объекта IServerWebConfig интерфейса, использовать <xref:System.EnterpriseServices.Internal.Publish>класса, который реализует <xref:System.EnterpriseServices.Internal.IComSoapPublisher>интерфейса.</xref:System.EnterpriseServices.Internal.IComSoapPublisher> </xref:System.EnterpriseServices.Internal.Publish>       IServerWebConfig используется внутренне платформой .NET Framework. Необходимо непосредственно использовать его в коде."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("6261e4b5-572a-4142-a2f9-1fe1a0c97097")]

      public interface IServerWebConfig
  implements: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Добавляет элементы XML в файл Web.config для COM-интерфейса, публикуемых в приложении COM + с поддержкой протокола SOAP."
  remarks: "В разделе <xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A>метод деталей реализации.</xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A> Тем не менее, необходимо вызвать `AddElement` метод непосредственно."
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string Mode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Путь для существующего файла Web.config."
    - id: AssemblyName
      type: System.String
      description: "Имя сборки, содержащей добавляемый тип."
    - id: TypeName
      type: System.String
      description: "Имя добавляемого типа."
    - id: ProgId
      type: System.String
      description: "Программный идентификатор добавляемого типа."
    - id: Mode
      type: System.String
      description: "Строковая константа, соответствующий имени члена из <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> перечисления, который указывает, как активировать хорошо известного объекта."
    - id: Error
      type: System.String
      description: "Строка, в который могут записываться сообщение об ошибке."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Создает файл Web.config для приложения COM + с поддержкой протокола SOAP, чтобы он готов к XML-элементов для публикуемых COM-интерфейсов."
  remarks: "В разделе <xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A>метод деталей реализации.</xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A> Тем не менее, необходимо вызвать `Create` напрямую."
  syntax:
    content: public void Create (string FilePath, string FileRootName, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Папка, в которой требуется создать файл конфигурации."
    - id: FileRootName
      type: System.String
      description: "Строковое значение, к которому могут добавляться расширение config (например, файл Web.config веб-сайта)."
    - id: Error
      type: System.String
      description: "Строка, в который могут записываться сообщение об ошибке."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: IServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create
  nameWithType: IServerWebConfig.Create
