### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement
  id: PeerCustomResolverElement
  children:
  - System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Address
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
  - System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
  - System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
  langs:
  - csharp
  name: PeerCustomResolverElement
  nameWithType: PeerCustomResolverElement
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement
  type: Class
  summary: "Представляет элемент конфигурации для настраиваемого распознавателя одноранговых узлов."
  syntax:
    content: 'public sealed class PeerCustomResolverElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: PeerCustomResolverElement()
  nameWithType: PeerCustomResolverElement.PeerCustomResolverElement()
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.PeerCustomResolverElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Инициализирует новый экземпляр по умолчанию <xref href=&quot;System.ServiceModel.Configuration.PeerCustomResolverElement&quot;> </xref> класса."
  syntax:
    content: public PeerCustomResolverElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Address
  id: Address
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Address
  nameWithType: PeerCustomResolverElement.Address
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Address
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Содержит URI схемы, используемой для XML-ФАЙЛ конфигурации пользовательского однорангового распознавателя."
  syntax:
    content: public Uri Address { get; set; }
    return:
      type: System.Uri
      description: "URI схемы, используемой для XML-ФАЙЛ конфигурации пользовательского однорангового распознавателя."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Address*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
  id: Binding
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Binding
  nameWithType: PeerCustomResolverElement.Binding
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Возвращает и задает имя строковой привязки, используемой для настраиваемого распознавателя одноранговых узлов."
  syntax:
    content: public string Binding { get; set; }
    return:
      type: System.String
      description: "Имя строковой привязки, используемой для настраиваемого распознавателя одноранговых узлов."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
  id: BindingConfiguration
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: BindingConfiguration
  nameWithType: PeerCustomResolverElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Возвращает и задает строку конфигурации привязки, используемой для настраиваемого распознавателя одноранговых узлов."
  syntax:
    content: public string BindingConfiguration { get; set; }
    return:
      type: System.String
      description: "Строка конфигурации привязки для настраиваемого распознавателя одноранговых узлов."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
  id: Headers
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Headers
  nameWithType: PeerCustomResolverElement.Headers
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Возвращает элемент конфигурации, в котором задается коллекция, содержащая заголовки, используемые для сообщений SOAP, обрабатываемых настраиваемым распознавателем одноранговых узлов."
  syntax:
    content: public System.ServiceModel.Configuration.AddressHeaderCollectionElement Headers { get; }
    return:
      type: System.ServiceModel.Configuration.AddressHeaderCollectionElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.AddressHeaderCollectionElement&quot;></xref>в котором задается коллекция, содержащая заголовки, используемые для сообщений SOAP, обрабатываемых настраиваемым распознавателем одноранговых узлов."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
  id: Identity
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Identity
  nameWithType: PeerCustomResolverElement.Identity
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Возвращает удостоверение настраиваемых распознавателей одноранговых настроенных для данного элемента."
  syntax:
    content: public System.ServiceModel.Configuration.IdentityElement Identity { get; }
    return:
      type: System.ServiceModel.Configuration.IdentityElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.IdentityElement&quot;></xref>содержащий удостоверение настраиваемых распознавателей одноранговых настроенных для данного элемента."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Properties
  nameWithType: PeerCustomResolverElement.Properties
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Для добавления."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
  id: ResolverType
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: ResolverType
  nameWithType: PeerCustomResolverElement.ResolverType
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Возвращает и задает значение типа string, содержащее «тип» настраиваемого распознавателя одноранговых узлов."
  syntax:
    content: public string ResolverType { get; set; }
    return:
      type: System.String
      description: "Строковое значение, содержащее «тип» настраиваемого распознавателя одноранговых узлов."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: PeerCustomResolverElement()
  nameWithType: PeerCustomResolverElement.PeerCustomResolverElement()
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.PeerCustomResolverElement()
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Address
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverElement.Address
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Address
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverElement.Binding
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: PeerCustomResolverElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Headers
  nameWithType: PeerCustomResolverElement.Headers
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: AddressHeaderCollectionElement
  nameWithType: AddressHeaderCollectionElement
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Identity
  nameWithType: PeerCustomResolverElement.Identity
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
- uid: System.ServiceModel.Configuration.IdentityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: IdentityElement
  nameWithType: IdentityElement
  fullName: System.ServiceModel.Configuration.IdentityElement
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Properties
  nameWithType: PeerCustomResolverElement.Properties
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: ResolverType
  nameWithType: PeerCustomResolverElement.ResolverType
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: PeerCustomResolverElement
  nameWithType: PeerCustomResolverElement.PeerCustomResolverElement
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Address*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverElement.Address
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverElement.Binding
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: PeerCustomResolverElement.BindingConfiguration
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Headers
  nameWithType: PeerCustomResolverElement.Headers
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Identity
  nameWithType: PeerCustomResolverElement.Identity
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Properties
  nameWithType: PeerCustomResolverElement.Properties
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: ResolverType
  nameWithType: PeerCustomResolverElement.ResolverType
