### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  id: NamedPipeConnectionPoolSettings
  children:
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettings
  nameWithType: NamedPipeConnectionPoolSettings
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  type: Class
  summary: "Представляет параметры, которые управляют поведением пула подключений именованного канала."
  syntax:
    content: public sealed class NamedPipeConnectionPoolSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  id: GroupName
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Возвращает или задает имя группы пула подключений на стороне клиента."
  remarks: "Значение по умолчанию можно изменить, чтобы изолировать подключения для конкретного клиента в отдельные группы."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "Имя группы пула подключений на стороне клиента. Имя по умолчанию — «default»."
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "Значение равно <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Возвращает или задает максимальное время которого подключение может простаивать в пуле подключений до отключения."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Возвращает <xref:System.TimeSpan>структуры, указывающее максимальное время подключение может простаивать в пуле подключений до отключения.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Значение меньше нуля."
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Возвращает или задает максимальное число исходящих подключений для каждой конечной точки, которая кэшируется в пуле соединений."
  remarks: "Это ограничивает число подключений, кэшируемых для каждой уникальной конечной точки. Если это значение превышается при наличии большего числа активных соединений клиентов, затем служба может не отвечать клиенту, и это значение следует скорректировать, чтобы превышает максимальное число ожидаемых подключений, кэшируемых для каждой уникальной конечной точки."
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "Максимальное число разрешенных исходящих подключений для каждой конечной точки, которая кэшируется в пуле соединений. Значение по умолчанию — 10."
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Значение меньше или равно нулю."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
