### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpListenerTimeoutsElement
  id: HttpListenerTimeoutsElement
  children:
  - System.Net.Configuration.HttpListenerTimeoutsElement.#ctor
  - System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  - System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  - System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  - System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  - System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  - System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  - System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  langs:
  - csharp
  name: HttpListenerTimeoutsElement
  nameWithType: HttpListenerTimeoutsElement
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement
  type: Class
  summary: "Представляет <xref href=&quot;System.Net.HttpListener&quot;> </xref> элемент времени ожидания в файле конфигурации. Этот класс не наследуется."
  remarks: "Элемент тайм-ауты определяет ограничения времени ожидания соединения dafault для <xref:System.Net.HttpListener>экземпляра.</xref:System.Net.HttpListener>"
  syntax:
    content: 'public sealed class HttpListenerTimeoutsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: HttpListenerTimeoutsElement()
  nameWithType: HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Net.Configuration.HttpListenerTimeoutsElement&quot;> </xref> класса."
  syntax:
    content: public HttpListenerTimeoutsElement ();
    parameters: []
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  id: DrainEntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: DrainEntityBody
  nameWithType: HttpListenerTimeoutsElement.DrainEntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Возвращает время в секундах, отводимое <xref href=&quot;System.Net.HttpListener&quot;> </xref> истощения тела сообщения для поддержания активности соединения."
  remarks: "Для поддержания активности соединения после отправки ответа на запрос приложения и полностью пришло тело сущности запроса <xref:System.Net.HttpListener>начинается сток оставшейся части тела сообщения до другого потенциально конвейерная запрос от клиента.</xref:System.Net.HttpListener> Если время истощения оставшиеся тела сообщения превышает допустимый период ожидания соединения."
  syntax:
    content: public TimeSpan DrainEntityBody { get; }
    return:
      type: System.TimeSpan
      description: "Возвращает <xref:System.TimeSpan>.</xref:System.TimeSpan>       Время в секундах, отводимое <xref href=&quot;System.Net.HttpListener&quot;> </xref> истощения тела сообщения для поддержания активности соединения."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  id: EntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: EntityBody
  nameWithType: HttpListenerTimeoutsElement.EntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Получает время в секундах, отводимое поступления тело сущности запроса."
  remarks: "<xref:System.Net.HttpListener>Включает этот таймер при запросе имеет тело сущности.</xref:System.Net.HttpListener> Истечение срока действия таймера изначально присваивается заданное значение. При <xref:System.Net.HttpListener>получает дополнительные данные указывают на запрос, он сбрасывает таймер, чтобы предоставить другой интервал подключения.</xref:System.Net.HttpListener>"
  syntax:
    content: public TimeSpan EntityBody { get; }
    return:
      type: System.TimeSpan
      description: "Возвращает <xref:System.TimeSpan>.</xref:System.TimeSpan>       Время, отводимое поступления тело сущности запроса."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  id: HeaderWait
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: HeaderWait
  nameWithType: HttpListenerTimeoutsElement.HeaderWait
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Возвращает время в секундах, отводимое <xref href=&quot;System.Net.HttpListener&quot;> </xref> выполнить синтаксический анализ заголовка запроса."
  remarks: "Это время ожидания применяется только после первого запроса на соединение направляется на <xref:System.Net.HttpListener>.</xref:System.Net.HttpListener>       Системе не удается определить очередь запросов или группу URL-адрес, сопоставленный запрос, пока не было проанализировано заголовки. Таким образом <xref:System.Net.HttpListener>применяет по умолчанию <xref:System.Net.HttpListenerTimeoutManager.HeaderWait%2A>таймера для первого запроса на соединение.</xref:System.Net.HttpListenerTimeoutManager.HeaderWait%2A> </xref:System.Net.HttpListener> Последующие запросы на открытое подключение будет использовать значение, заданное для этого свойства."
  syntax:
    content: public TimeSpan HeaderWait { get; }
    return:
      type: System.TimeSpan
      description: "Возвращает <xref:System.TimeSpan>.</xref:System.TimeSpan>       Время в секундах, отводимое <xref href=&quot;System.Net.HttpListener&quot;> </xref> выполнить синтаксический анализ заголовка запроса."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  id: IdleConnection
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: IdleConnection
  nameWithType: HttpListenerTimeoutsElement.IdleConnection
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Получает время в секундах, отводимое бездействующее подключение."
  remarks: "Это время ожидания применяется только после первого запроса на соединение направляется на <xref:System.Net.HttpListener>.</xref:System.Net.HttpListener>       Системе не удается определить очередь запросов или группу URL-адрес, сопоставленный запрос, пока не было проанализировано заголовки. Таким образом <xref:System.Net.HttpListener>применяет по умолчанию <xref:System.Net.HttpListenerTimeoutManager.IdleConnection%2A>таймера для первого запроса на соединение.</xref:System.Net.HttpListenerTimeoutManager.IdleConnection%2A> </xref:System.Net.HttpListener> Последующие запросы на открытое подключение будет использовать значение, заданное для этого свойства."
  syntax:
    content: public TimeSpan IdleConnection { get; }
    return:
      type: System.TimeSpan
      description: "Возвращает <xref:System.TimeSpan>.</xref:System.TimeSpan>       Время в секундах для неактивного подключения."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  id: MinSendBytesPerSecond
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: MinSendBytesPerSecond
  nameWithType: HttpListenerTimeoutsElement.MinSendBytesPerSecond
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Получает минимальная скорость отправки, в байтах в секунду, для ответа."
  syntax:
    content: public long MinSendBytesPerSecond { get; }
    return:
      type: System.Int64
      description: "Возвращает <xref:System.Int64>.</xref:System.Int64>       Скорость минимальное отправки в байтах в секунду, для ответа."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpListenerTimeoutsElement.Properties
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Для добавления."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  id: RequestQueue
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: RequestQueue
  nameWithType: HttpListenerTimeoutsElement.RequestQueue
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Возвращает время в секундах, разрешенный для запроса должен храниться в очереди запросов перед <xref href=&quot;System.Net.HttpListener&quot;> </xref> принимает сообщение."
  syntax:
    content: public TimeSpan RequestQueue { get; }
    return:
      type: System.TimeSpan
      description: "Возвращает <xref:System.TimeSpan>.</xref:System.TimeSpan>       Время в секундах, разрешенный для запроса должен храниться в очереди запросов перед <xref href=&quot;System.Net.HttpListener&quot;> </xref> принимает сообщение."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HttpListenerTimeoutsElement()
  nameWithType: HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: DrainEntityBody
  nameWithType: HttpListenerTimeoutsElement.DrainEntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: EntityBody
  nameWithType: HttpListenerTimeoutsElement.EntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HeaderWait
  nameWithType: HttpListenerTimeoutsElement.HeaderWait
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: IdleConnection
  nameWithType: HttpListenerTimeoutsElement.IdleConnection
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: MinSendBytesPerSecond
  nameWithType: HttpListenerTimeoutsElement.MinSendBytesPerSecond
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HttpListenerTimeoutsElement.Properties
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: RequestQueue
  nameWithType: HttpListenerTimeoutsElement.RequestQueue
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HttpListenerTimeoutsElement
  nameWithType: HttpListenerTimeoutsElement.HttpListenerTimeoutsElement
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: DrainEntityBody
  nameWithType: HttpListenerTimeoutsElement.DrainEntityBody
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: EntityBody
  nameWithType: HttpListenerTimeoutsElement.EntityBody
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HeaderWait
  nameWithType: HttpListenerTimeoutsElement.HeaderWait
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: IdleConnection
  nameWithType: HttpListenerTimeoutsElement.IdleConnection
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: MinSendBytesPerSecond
  nameWithType: HttpListenerTimeoutsElement.MinSendBytesPerSecond
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.Properties*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HttpListenerTimeoutsElement.Properties
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: RequestQueue
  nameWithType: HttpListenerTimeoutsElement.RequestQueue
