### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.WebRequestModuleElement
  id: WebRequestModuleElement
  children:
  - System.Net.Configuration.WebRequestModuleElement.#ctor
  - System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  - System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  - System.Net.Configuration.WebRequestModuleElement.Prefix
  - System.Net.Configuration.WebRequestModuleElement.Properties
  - System.Net.Configuration.WebRequestModuleElement.Type
  langs:
  - csharp
  name: WebRequestModuleElement
  nameWithType: WebRequestModuleElement
  fullName: System.Net.Configuration.WebRequestModuleElement
  type: Class
  summary: "Представляет префикс URI и соответствующий класс, обрабатывающий создание веб-запросов в качестве префикса. Этот класс не наследуется."
  remarks: "Using the <xref:System.Net.WebRequest> and <xref:System.Net.WebResponse> classes, applications can request resources for any valid <xref:System.Uri>. Use this configuration element to specify a module that is registered to work with the <xref:System.Net.WebRequest.Create%2A> overloads to create new requests.  \n  \n This class corresponds to the [\\&lt;add\\&gt; Element for webRequestModules (Network Settings)](../Topic/%3Cadd%3E%20Element%20for%20webRequestModules%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify modules registered to authenticate requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files.  \n  \n The .NET Framework version 2.0 provides Web request modules that create requests for resources with the following prefixes:  \n  \n-   HTTP  \n  \n-   HTTPS  \n  \n-   FTP  \n  \n-   FILE"
  syntax:
    content: 'public sealed class WebRequestModuleElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement()
  nameWithType: WebRequestModuleElement.WebRequestModuleElement()
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Net.Configuration.WebRequestModuleElement&quot;> </xref> класса."
  syntax:
    content: public WebRequestModuleElement ();
    parameters: []
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement(String,String)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,String)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Net.Configuration.WebRequestModuleElement&quot;> </xref> класса, используя указанные префикс URI данные типа."
  remarks: "`type` Параметр содержит имя полного имени типа, за которым следует запятая (,) и сведения о сборке. Сведения о сборке элементы разделяются запятыми, например, «`System.Net.DigestClient, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;`.       <xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>Свойству `prefix` и <xref:System.Net.Configuration.WebRequestModuleElement.Type%2A>свойству `type`.</xref:System.Net.Configuration.WebRequestModuleElement.Type%2A> </xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>"
  syntax:
    content: public WebRequestModuleElement (string prefix, string type);
    parameters:
    - id: prefix
      type: System.String
      description: "Строка, содержащая префикс URI."
    - id: type
      type: System.String
      description: "Строка, содержащая данные типа и сборки для класса, который управляет Создание запросов для ресурсов, использующих `prefix` префикс URI. Дополнительные сведения см. в разделе «Примечания»."
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  id: '#ctor(System.String,System.Type)'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement(String,Type)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,Type)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Net.Configuration.WebRequestModuleElement&quot;> </xref> класса, используя указанный префикс URI и идентификатор типа."
  remarks: "<xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>Свойству `prefix` и <xref:System.Net.Configuration.WebRequestModuleElement.Type%2A>свойству `type`.</xref:System.Net.Configuration.WebRequestModuleElement.Type%2A> </xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>"
  syntax:
    content: public WebRequestModuleElement (string prefix, Type type);
    parameters:
    - id: prefix
      type: System.String
      description: "Строка, содержащая префикс URI."
    - id: type
      type: System.Type
      description: "Объект <xref:System.Type>класс, который определяет, обрабатывает запросы на создание для ресурсов, использующих `prefix` префикс URI.</xref:System.Type>"
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix
  id: Prefix
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
  fullName: System.Net.Configuration.WebRequestModuleElement.Prefix
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Возвращает или задает префикс URI для текущего модуля веб-запросов."
  remarks: "Платформа .NET Framework версии 2.0 предоставляет модули веб-запросов, которые создают запросы к ресурсам со следующими префиксами: - HTTP - HTTPS - FTP - файла"
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "Строка, содержащая префикс URI."
  overload: System.Net.Configuration.WebRequestModuleElement.Prefix*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.Properties
  id: Properties
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
  fullName: System.Net.Configuration.WebRequestModuleElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Для добавления."
  overload: System.Net.Configuration.WebRequestModuleElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.Type
  id: Type
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Type
  nameWithType: WebRequestModuleElement.Type
  fullName: System.Net.Configuration.WebRequestModuleElement.Type
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Возвращает или задает класс, который создает веб-запросы."
  remarks: "С помощью <xref:System.Net.WebRequest>и <xref:System.Net.WebResponse>классы, приложения могут запрашивать ресурсы для любой допустимый <xref:System.Uri>.</xref:System.Uri> </xref:System.Net.WebResponse> </xref:System.Net.WebRequest> Это свойство используется для указания типа, зарегистрированных для работы с <xref:System.Net.WebRequest.Create%2A>метод для создания новых запросов.</xref:System.Net.WebRequest.Create%2A>       Платформа .NET Framework версии 2.0 предоставляет модули веб-запросов, которые создают запросы к ресурсам со следующими префиксами: - HTTP - HTTPS - FTP - файла"
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "Объект <xref:System.Type>экземпляр, определяющий веб-запроса модуль.</xref:System.Type>"
  overload: System.Net.Configuration.WebRequestModuleElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement()
  nameWithType: WebRequestModuleElement.WebRequestModuleElement()
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement()
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement(String,String)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,String)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement(String,Type)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,Type)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
  fullName: System.Net.Configuration.WebRequestModuleElement.Prefix
- uid: System.Net.Configuration.WebRequestModuleElement.Properties
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
  fullName: System.Net.Configuration.WebRequestModuleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.WebRequestModuleElement.Type
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Type
  nameWithType: WebRequestModuleElement.Type
  fullName: System.Net.Configuration.WebRequestModuleElement.Type
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement
  nameWithType: WebRequestModuleElement.WebRequestModuleElement
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
- uid: System.Net.Configuration.WebRequestModuleElement.Properties*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
- uid: System.Net.Configuration.WebRequestModuleElement.Type*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Type
  nameWithType: WebRequestModuleElement.Type
