### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig
  id: ClientRemotingConfig
  children:
  - System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  - System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  langs:
  - csharp
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig
  type: Class
  summary: "Определяет статическое <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>метод, который создает клиентский файл конфигурации удаленного взаимодействия для клиентскую библиотеку типов.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>"
  remarks: "<xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>Используется метод <xref:System.EnterpriseServices.Internal.Publish>класса при создании COM-интерфейса из библиотеки типов клиента (с расширением TLB).</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> <xref:System.EnterpriseServices.Internal.Publish>Класс публикует COM-интерфейсы в приложение COM + с поддержкой протокола SOAP.</xref:System.EnterpriseServices.Internal.Publish> Один из параметров данного метода, имя сборки, содержащую метаданные среды выполнения (CLR), <xref:System.EnterpriseServices.Internal.Publish>уже создан для клиентской библиотеки типов.</xref:System.EnterpriseServices.Internal.Publish>       <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>не должен вызываться напрямую.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> Вместо этого необходимо вызовите <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>метод <xref:System.EnterpriseServices.Internal.Publish>класса.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       ClientRemotingConfig используется внутренне платформой .NET Framework. Необходимо использовать класс непосредственно в коде."
  syntax:
    content: public class ClientRemotingConfig
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.EnterpriseServices.Internal.ClientRemotingConfig&quot;> </xref> класса."
  syntax:
    content: public ClientRemotingConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  id: Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Создает клиентский файл конфигурации удаленного взаимодействия для клиентскую библиотеку типов в приложении COM + с поддержкой протокола SOAP."
  remarks: "Статический метод записи вызывается методом <xref:System.EnterpriseServices.Internal.Publish>класса при создании COM-интерфейса из библиотеки типов клиента (с расширением TLB).</xref:System.EnterpriseServices.Internal.Publish> <xref:System.EnterpriseServices.Internal.Publish>Класс публикует COM-интерфейсы в приложение COM + с поддержкой протокола SOAP.</xref:System.EnterpriseServices.Internal.Publish>       Записи не должен вызываться напрямую. Вместо этого необходимо вызовите <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>метод <xref:System.EnterpriseServices.Internal.Publish>класса.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       `BaseUrl` И `VRoot` объединяется значения параметров (с использованием разделителя пути, при необходимости) формы клиентский элемент `URL` значение атрибута.       `AssemblyName` Параметр идентифицирует сборку, содержащую метаданные среды CLR, <xref:System.EnterpriseServices.Internal.Publish>, с использованием <xref:System.EnterpriseServices.Internal.GenerateMetadata>класса, уже создан для клиентской библиотеки типов.</xref:System.EnterpriseServices.Internal.GenerateMetadata> </xref:System.EnterpriseServices.Internal.Publish>"
  syntax:
    content: public static bool Write (string DestinationDirectory, string VRoot, string BaseUrl, string AssemblyName, string TypeName, string ProgId, string Mode, string Transport);
    parameters:
    - id: DestinationDirectory
      type: System.String
      description: "Папка, в которой требуется создать файл конфигурации."
    - id: VRoot
      type: System.String
      description: "Имя виртуального корневого каталога."
    - id: BaseUrl
      type: System.String
      description: "Базовый URL-адрес, содержащий виртуальный корень."
    - id: AssemblyName
      type: System.String
      description: "Отображаемое имя сборки, содержащую метаданные среды выполнения (CLR) соответствующие библиотеки типов."
    - id: TypeName
      type: System.String
      description: "Полное имя сборки, которая содержит метаданные среды CLR, соответствующие библиотеке типов."
    - id: ProgId
      type: System.String
      description: "Программный идентификатор класса."
    - id: Mode
      type: System.String
      description: "Режим активации."
    - id: Transport
      type: System.String
      description: "Не используется. Укажите <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> для этого параметра."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>файл конфигурации удаленного взаимодействия клиента был успешно создан; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig.ClientRemotingConfig
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write
  nameWithType: ClientRemotingConfig.Write
