### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement
  id: BindingElementExtensionElement
  children:
  - System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor
  - System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
  - System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement
  - System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  langs:
  - csharp
  name: BindingElementExtensionElement
  nameWithType: BindingElementExtensionElement
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement
  type: Class
  summary: "Позволяет использовать настраиваемый <xref:System.ServiceModel.Channels.BindingElement>реализацию с компьютера или файле конфигурации приложения.</xref:System.ServiceModel.Channels.BindingElement>"
  remarks: "Должен быть производным от класса BindingElementExtensionElement класс для использования пользовательского <xref:System.ServiceModel.Channels.BindingElement>реализацию с компьютера или файле конфигурации приложения.</xref:System.ServiceModel.Channels.BindingElement>       После создания экземпляра класса BindingElementExtensionElement возвращается элемент пользовательской привязки. Можно использовать это в файле конфигурации приложения с помощью `add`настроек элемент и тип параметра атрибута класса BindingElementExtensionElement класс и атрибут name для пользовательского элемента привязки."
  syntax:
    content: 'public abstract class BindingElementExtensionElement : System.ServiceModel.Configuration.ServiceModelExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: BindingElementExtensionElement()
  nameWithType: BindingElementExtensionElement.BindingElementExtensionElement()
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementExtensionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.ServiceModel.Configuration.BindingElementExtensionElement&quot;> </xref> класса."
  syntax:
    content: protected BindingElementExtensionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  id: ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: ApplyConfiguration(BindingElement)
  nameWithType: BindingElementExtensionElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Применяет содержимое указанного элемента привязки к данному элементу конфигурации привязки."
  syntax:
    content: public virtual void ApplyConfiguration (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "Элемент привязки."
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>bindingElement</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: BindingElementExtensionElement.BindingElementType
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "При переопределении в производном классе, возвращает <xref:System.Type>, представляющий элемент настраиваемой привязки.</xref:System.Type>"
  remarks: "Переопределите и реализуйте свойство BindingElementType для возвращения типа элемента пользовательской привязки, это <xref:System.ServiceModel.Configuration.BindingElementExtensionElement>связывает с системой конфигурации.</xref:System.ServiceModel.Configuration.BindingElementExtensionElement>"
  syntax:
    content: public abstract Type BindingElementType { get; }
    return:
      type: System.Type
      description: "Объект <xref:System.Type>, представляющий тип настраиваемой привязки.</xref:System.Type>"
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement
  id: CreateBindingElement
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: CreateBindingElement()
  nameWithType: BindingElementExtensionElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "При переопределении в производном классе Возвращает настраиваемый объект элемента привязки."
  syntax:
    content: protected abstract System.ServiceModel.Channels.BindingElement CreateBindingElement ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.BindingElement
      description: "Настраиваемый <xref:System.ServiceModel.Channels.BindingElement>объекта.</xref:System.ServiceModel.Channels.BindingElement>"
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  id: InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: InitializeFrom(BindingElement)
  nameWithType: BindingElementExtensionElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Инициализирует этот раздел конфигурации привязки с помощью содержимого заданного элемента привязки."
  syntax:
    content: protected virtual void InitializeFrom (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "Элемент привязки."
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: BindingElementExtensionElement()
  nameWithType: BindingElementExtensionElement.BindingElementExtensionElement()
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementExtensionElement()
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: ApplyConfiguration(BindingElement)
  nameWithType: BindingElementExtensionElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(BindingElement)
- uid: System.ServiceModel.Channels.BindingElement
  parent: System.ServiceModel.Channels
  isExternal: true
  name: BindingElement
  nameWithType: BindingElement
  fullName: System.ServiceModel.Channels.BindingElement
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: BindingElementType
  nameWithType: BindingElementExtensionElement.BindingElementType
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: CreateBindingElement()
  nameWithType: BindingElementExtensionElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement()
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: InitializeFrom(BindingElement)
  nameWithType: BindingElementExtensionElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(BindingElement)
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: BindingElementExtensionElement
  nameWithType: BindingElementExtensionElement.BindingElementExtensionElement
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: BindingElementExtensionElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: BindingElementType
  nameWithType: BindingElementExtensionElement.BindingElementType
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: CreateBindingElement
  nameWithType: BindingElementExtensionElement.CreateBindingElement
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: InitializeFrom
  nameWithType: BindingElementExtensionElement.InitializeFrom
