### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.IApplicationPreloadUtil
  id: IApplicationPreloadUtil
  children:
  - System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  - System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  langs:
  - csharp
  name: IApplicationPreloadUtil
  nameWithType: IApplicationPreloadUtil
  fullName: System.Web.Hosting.IApplicationPreloadUtil
  type: Interface
  summary: "Предоставляет методы, используемые для взаимодействия с платформой ASP.NET [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] хотя сервер приложения выполняет предварительную загрузку."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("940D8ADD-9E40-4475-9A67-2CDCDF57995C")]

      [System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]

      public interface IApplicationPreloadUtil
  implements: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  id: GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  langs:
  - csharp
  name: GetApplicationPreloadInfo(String,Boolean,String,String[])
  nameWithType: IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
  fullName: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Возвращает данные инициализации, необходимые для предварительной загрузки приложения. Этот метод вызывается ASP.NET."
  syntax:
    content: public void GetApplicationPreloadInfo (string context, out bool enabled, out string startupObjType, out string[] parametersForStartupObj);
    parameters:
    - id: context
      type: System.String
      description: "Контекст приложения."
    - id: enabled
      type: System.Boolean
      description: "При возвращении этого метода содержит <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref> для указания, что приложение должно быть предварительно загруженных; в противном случае — <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Этот параметр передается неинициализированным."
    - id: startupObjType
      type: System.String
      description: "По возвращении из этого метода содержит строку, которая идентифицирует управляемого типа, который является частью процесса предварительной загрузки. Этот параметр передается неинициализированным."
    - id: parametersForStartupObj
      type: System.String[]
      description: "По возвращении из этого метода содержит данные, которые будут переданы предварительно загруженных типа. Этот параметр передается неинициализированным."
  overload: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  id: ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  langs:
  - csharp
  name: ReportApplicationPreloadFailure(String,Int32,String)
  nameWithType: IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
  fullName: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Отчеты, произошла ошибка в [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] при загрузке сервером приложения ASP.NET."
  syntax:
    content: public void ReportApplicationPreloadFailure (string context, int errorCode, string errorMessage);
    parameters:
    - id: context
      type: System.String
      description: "Контекст приложения."
    - id: errorCode
      type: System.Int32
      description: "Числовой код ошибки."
    - id: errorMessage
      type: System.String
      description: "Текст ошибки."
  overload: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: GetApplicationPreloadInfo(String,Boolean,String,String[])
  nameWithType: IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
  fullName: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: ReportApplicationPreloadFailure(String,Int32,String)
  nameWithType: IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
  fullName: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo*
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: GetApplicationPreloadInfo
  nameWithType: IApplicationPreloadUtil.GetApplicationPreloadInfo
- uid: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure*
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: ReportApplicationPreloadFailure
  nameWithType: IApplicationPreloadUtil.ReportApplicationPreloadFailure
