### YamlMime:ManagedReference
items:
- uid: System.Configuration.UserScopedSettingAttribute
  id: UserScopedSettingAttribute
  children:
  - System.Configuration.UserScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute
  fullName: System.Configuration.UserScopedSettingAttribute
  type: Class
  summary: "Указывает, что группы параметров приложения или свойства содержит уникальных значений для каждого пользователя приложения. Этот класс не наследуется."
  remarks: "Свойства параметров приложения имеют область, которая основывается либо на уровне пользователя или приложения. Категории подразумевают, приложения имеют одинаковые значения для всех пользователей приложения, тогда как области пользователей имеют разные значения для каждого пользователя приложения.       UserScopedSettingAttribute указывает, что свойство должно считаться параметром уровня пользователя и, соответствующих дисковых решения должно выполняться соответствующим образом поставщика параметров.       Атрибут области требуется для каждого свойства параметров приложения. Если свойство не применяется к одному <xref:System.Configuration.ApplicationScopedSettingAttribute>или UserScopedSettingAttribute, свойство учитывается поставщиком параметров, не сериализуется.</xref:System.Configuration.ApplicationScopedSettingAttribute> Тем не менее, недопустимо использование двух атрибутов для одного свойства параметров. Такой сбой вызовет <xref:System.Configuration.ConfigurationErrorsException>исключение.</xref:System.Configuration.ConfigurationErrorsException>"
  example:
  - "The following code example demonstrates the use of the UserScopedSettingAttribute applied to all four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.u_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.u_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class UserScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.UserScopedSettingAttribute
  langs:
  - csharp
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Configuration.UserScopedSettingAttribute&quot;> </xref> класса."
  remarks: "Каждое свойство параметров должен применяться с одной областью атрибутом для того чтобы распознаваться и сериализации поставщика параметров."
  syntax:
    content: public UserScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.UserScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
- uid: System.Configuration.UserScopedSettingAttribute.#ctor*
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute
