### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsProtectionEnum
  id: FormsProtectionEnum
  children:
  - System.Web.Configuration.FormsProtectionEnum.All
  - System.Web.Configuration.FormsProtectionEnum.Encryption
  - System.Web.Configuration.FormsProtectionEnum.None
  - System.Web.Configuration.FormsProtectionEnum.Validation
  langs:
  - csharp
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
  type: Enum
  summary: "Определяет тип шифрования, если таковые имеются, для файлов cookie."
  remarks: "Если выбрать все значения, система использует алгоритм проверки настроенных данных на основе [machineKey (схема параметров ASP.NET) элемент](http://msdn.microsoft.com/en-us/4b5699a9-bc21-4c4a-85f1-8b3b8ebd2d46) тег. Это значение по умолчанию и рекомендуемым значением.       Если выбрано значение None, файлы cookie могут подвергнуться атакам с открытым текстом.       При выборе проверки куки-файл создается с помощью проверки cookie путем сцепления ключа проверки с данными cookie, вычисления кода проверки подлинности сообщения (MAC) и добавления MAC в исходящий файл cookie."
  example:
  - "The following code example shows how to use the FormsProtectionEnum enumeration. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationConfiguration> class topic to learn how to get the section.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/visualbasic/t-system.web.configurati_72_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/csharp/t-system.web.configurati_72_1.cs)]"
  syntax:
    content: public enum FormsProtectionEnum
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.All
  id: All
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что приложение использовать проверки данных и шифрования для защиты файлов cookie. Этот параметр использует алгоритм проверки настроенных данных (на основе <xref uid=&quot;langword_csharp_machineKey&quot; name=&quot;machineKey&quot; href=&quot;&quot;> </xref> элемент). Triple-DES (3DES) используется для шифрования, если он доступен и если ключ не менее 48 байт. <xref uid=&quot;langword_csharp_All&quot; name=&quot;All&quot; href=&quot;&quot;></xref>значение по умолчанию (и рекомендуемое) значение."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  id: Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что файлы cookie, шифруются с помощью Triple-DES или DES, но проверка данных в файлы cookie не производится. Используемые таким образом файлы cookie могут подвергнуться избирательным атак на систему безопасности."
  syntax:
    content: Encryption
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.None
  id: None
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что шифрование и проверка отключены для сайтов, которые используют файлы cookie только для персонализации и имеют меньшие требования безопасности. Не рекомендуется использовать файлы Cookie таким образом; Однако это наименее ресурсоемкий способ включения персонализации с помощью .NET Framework."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  id: Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Указывает, что приложение использует схему проверки для проверки того, что не было изменено содержимое зашифрованного файла cookie во время передачи. Файл cookie создается путем сцепления ключа проверки с данными cookie, вычисления кода проверки подлинности сообщения (MAC) и добавления MAC в исходящий файл cookie."
  syntax:
    content: Validation
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FormsProtectionEnum.All
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
- uid: System.Web.Configuration.FormsProtectionEnum
  parent: System.Web.Configuration
  isExternal: false
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
- uid: System.Web.Configuration.FormsProtectionEnum.None
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
