### YamlMime:ManagedReference
items:
- uid: System.Configuration.ClientSettingsSection
  id: ClientSettingsSection
  children:
  - System.Configuration.ClientSettingsSection.#ctor
  - System.Configuration.ClientSettingsSection.Properties
  - System.Configuration.ClientSettingsSection.Settings
  langs:
  - csharp
  name: ClientSettingsSection
  nameWithType: ClientSettingsSection
  fullName: System.Configuration.ClientSettingsSection
  type: Class
  summary: "Представляет группу установок приложений пользователя в файле конфигурации."
  remarks: "[!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] Содержит параметры по умолчанию один поставщик, <xref:System.Configuration.LocalFileSettingsProvider>, который сохраняет данные конфигурации в локальной файловой системе в файлах с расширением `.config`.</xref:System.Configuration.LocalFileSettingsProvider> Содержимое файлов конфигурации структурированы в форме XML-документов. Параметры пользователя сохраняются в файл с именем `username.config`. В этом файле данные сохраняются как элементы внутри `<userSettings>` раздела. Каждый из них будет представлен соответствующий ClientSettingsSection. Каждый раздел объект принадлежит и управляется обработчик раздела конфигурации, который является <xref:System.Configuration.IConfigurationSectionHandler>.</xref:System.Configuration.IConfigurationSectionHandler>       Класс ClientSettingsSection представляет собой простое расширение <xref:System.Configuration.ConfigurationSection>класс, который используется в [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] поддержка файлов Общая конфигурация.</xref:System.Configuration.ConfigurationSection>       Дополнительные сведения о параметрах приложений см. в разделе [параметры приложения для Windows Forms](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: 'public sealed class ClientSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Configuration.ClientSettingsSection.#ctor
  id: '#ctor'
  parent: System.Configuration.ClientSettingsSection
  langs:
  - csharp
  name: ClientSettingsSection()
  nameWithType: ClientSettingsSection.ClientSettingsSection()
  fullName: System.Configuration.ClientSettingsSection.ClientSettingsSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Configuration.ClientSettingsSection&quot;> </xref> класса."
  remarks: "Инициализирует конструктор по умолчанию ClientSettingsSection <xref:System.Configuration.ClientSettingsSection.Settings%2A>свойство.</xref:System.Configuration.ClientSettingsSection.Settings%2A>"
  syntax:
    content: public ClientSettingsSection ();
    parameters: []
  overload: System.Configuration.ClientSettingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ClientSettingsSection.Properties
  id: Properties
  parent: System.Configuration.ClientSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ClientSettingsSection.Properties
  fullName: System.Configuration.ClientSettingsSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Для добавления."
  overload: System.Configuration.ClientSettingsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ClientSettingsSection.Settings
  id: Settings
  parent: System.Configuration.ClientSettingsSection
  langs:
  - csharp
  name: Settings
  nameWithType: ClientSettingsSection.Settings
  fullName: System.Configuration.ClientSettingsSection.Settings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Возвращает коллекцию параметров клиента для раздела."
  remarks: "Свойства параметров — это свойство конфигурации."
  syntax:
    content: public System.Configuration.SettingElementCollection Settings { get; }
    return:
      type: System.Configuration.SettingElementCollection
      description: "Объект <xref href=&quot;System.Configuration.SettingElementCollection&quot;> </xref> содержит все параметры клиента найден в текущем разделе конфигурации."
  overload: System.Configuration.ClientSettingsSection.Settings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Configuration.ClientSettingsSection.#ctor
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: ClientSettingsSection()
  nameWithType: ClientSettingsSection.ClientSettingsSection()
  fullName: System.Configuration.ClientSettingsSection.ClientSettingsSection()
- uid: System.Configuration.ClientSettingsSection.Properties
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Properties
  nameWithType: ClientSettingsSection.Properties
  fullName: System.Configuration.ClientSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ClientSettingsSection.Settings
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Settings
  nameWithType: ClientSettingsSection.Settings
  fullName: System.Configuration.ClientSettingsSection.Settings
- uid: System.Configuration.SettingElementCollection
  parent: System.Configuration
  isExternal: false
  name: SettingElementCollection
  nameWithType: SettingElementCollection
  fullName: System.Configuration.SettingElementCollection
- uid: System.Configuration.ClientSettingsSection.#ctor*
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: ClientSettingsSection
  nameWithType: ClientSettingsSection.ClientSettingsSection
- uid: System.Configuration.ClientSettingsSection.Properties*
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Properties
  nameWithType: ClientSettingsSection.Properties
- uid: System.Configuration.ClientSettingsSection.Settings*
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Settings
  nameWithType: ClientSettingsSection.Settings
