### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLocation
  id: ConfigurationLocation
  children:
  - System.Configuration.ConfigurationLocation.OpenConfiguration
  - System.Configuration.ConfigurationLocation.Path
  langs:
  - csharp
  name: ConfigurationLocation
  nameWithType: ConfigurationLocation
  fullName: System.Configuration.ConfigurationLocation
  type: Class
  summary: "Представляет <xref uid=&quot;langword_csharp_location&quot; name=&quot;location&quot; href=&quot;&quot;> </xref> элемент в файле конфигурации."
  remarks: "Экземпляр класса ConfigurationLocation представляет одно `location` элемент в файле конфигурации. Расположения, используемые для указания параметров конфигурации, которые применяются только к указанным ресурсам, например определенную страницу, файл или вложенная папка, в веб-приложения. Класс ConfigurationLocation используется для получения пути и <xref:System.Configuration.Configuration>объект, который применяется к определенному ресурсу.</xref:System.Configuration.Configuration>"
  example:
  - "In the following code example, the Web configuration for the application `MySampleApp` is loaded, and then the locations defined in the configuration are displayed.  \n  \n [!code-vb[ConfigurationLocationCollection#1](~/add/codesnippet/visualbasic/t-system.configuration.c_22_1.vb)]\n [!code-cs[ConfigurationLocationCollection#1](~/add/codesnippet/csharp/t-system.configuration.c_22_1.cs)]"
  syntax:
    content: public class ConfigurationLocation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  id: OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Создает экземпляр объекта конфигурации."
  syntax:
    content: public System.Configuration.Configuration OpenConfiguration ();
    parameters: []
    return:
      type: System.Configuration.Configuration
      description: "Объект конфигурации."
  overload: System.Configuration.ConfigurationLocation.OpenConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocation.Path
  id: Path
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Получает относительный путь к ресурсу, чьи параметры конфигурации представлены в этом <xref href=&quot;System.Configuration.ConfigurationLocation&quot;> </xref> объекта."
  remarks: "Путь, который возвращается свойством путь задается относительно корневого веб-узла.      Настроек [!NOTE] настроек свойство Path может содержать разделенный запятыми список путей, к которым применяется параметр конфигурации."
  example:
  - "The following code example shows how to access the Path property and display the value returned to the console.  \n  \n [!code-vb[ConfigurationLocationCollection#2](~/add/codesnippet/visualbasic/p-system.configuration.c_38_1.vb)]\n [!code-cs[ConfigurationLocationCollection#2](~/add/codesnippet/csharp/p-system.configuration.c_38_1.cs)]"
  syntax:
    content: public string Path { get; }
    return:
      type: System.String
      description: "Относительный путь к ресурсу, чьи параметры конфигурации представленный этим <xref href=&quot;System.Configuration.ConfigurationLocation&quot;> </xref>."
  overload: System.Configuration.ConfigurationLocation.Path*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Configuration.ConfigurationLocation.Path
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration*
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: OpenConfiguration
  nameWithType: ConfigurationLocation.OpenConfiguration
- uid: System.Configuration.ConfigurationLocation.Path*
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: Path
  nameWithType: ConfigurationLocation.Path
