### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFrameworkMissingException
  id: CompatibleFrameworkMissingException
  children:
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  - System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  langs:
  - csharp
  name: CompatibleFrameworkMissingException
  nameWithType: CompatibleFrameworkMissingException
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException
  type: Class
  summary: "Это исключение вызывается, когда не удается найти версию платформы .NET Framework, совместимую с этим приложением."
  syntax:
    content: 'public class CompatibleFrameworkMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> класс системным сообщением, содержащим описание ошибки."
  remarks: "Этот конструктор инициализирует <xref:System.Exception.Message%2A>свойство нового экземпляра системным сообщением, которое описывает ошибку, например «Не найдена совместимая среда.»</xref:System.Exception.Message%2A> Это сообщение учитывает текущую культуру системы.       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.</xref:System.Deployment.Application.CompatibleFrameworkMissingException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Строка локализованного сообщения об. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CompatibleFrameworkMissingException ();
    parameters: []
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> класса с указанным сообщением, содержащим описание ошибки."
  remarks: "В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.</xref:System.Deployment.Application.CompatibleFrameworkMissingException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке, указываемой `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CompatibleFrameworkMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, описывающее исключение. Код, вызывающий этот конструктор, должен убедиться, что эта строка локализована для текущего языка и региональных параметров системы."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> сериализованными данными."
  remarks: "Данный конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке."
  syntax:
    content: protected CompatibleFrameworkMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "Объект, содержащий сериализованные данные объекта."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "Контекстные сведения об источнике или назначении."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> класса с указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение."
  remarks: "Исключение, созданное как прямой результат предыдущего исключения, должно содержать ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Свойство возвращает то же значение, которое передается конструктору, или `null` Если <xref:System.Exception.InnerException%2A>свойства не предоставляет конструктору значение внутреннего исключения.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.</xref:System.Deployment.Application.CompatibleFrameworkMissingException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке, указываемой `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CompatibleFrameworkMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, описывающее исключение. Код, вызывающий этот конструктор, должен убедиться, что эта строка локализована для текущего языка и региональных параметров системы."
    - id: innerException
      type: System.Exception
      description: "Исключение, которое стало причиной текущего исключения. Если `innerException` не <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, текущее исключение сгенерировано в <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> блок, обрабатывающем внутреннее исключение."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  id: CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Получает список версий .NET Framework, где можно установить и запустить это приложение."
  syntax:
    content: public System.Deployment.Application.CompatibleFrameworks CompatibleFrameworks { get; }
    return:
      type: System.Deployment.Application.CompatibleFrameworks
      description: "Список версий .NET Framework, где можно установить и запустить это приложение."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> сериализованными данными."
  remarks: "Данный конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Объект, содержащий сериализованные данные объекта."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Контекстные сведения об источнике или назначении."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworks
  parent: System.Deployment.Application
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: CompatibleFrameworkMissingException.GetObjectData
