### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  id: TextExpressionCompilerSettings
  children:
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.#ctor
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.Activity
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityName
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityNamespace
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.AlwaysGenerateSource
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.ForImplementation
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.GenerateAsPartialClass
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.Language
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.LogSourceGenerationMessage
  - System.Activities.XamlIntegration.TextExpressionCompilerSettings.RootNamespace
  langs:
  - csharp
  name: TextExpressionCompilerSettings
  nameWithType: TextExpressionCompilerSettings
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  type: Class
  summary: "Задает параметры компилятора текста выражения."
  syntax:
    content: public class TextExpressionCompilerSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.#ctor
  id: '#ctor'
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: TextExpressionCompilerSettings()
  nameWithType: TextExpressionCompilerSettings.TextExpressionCompilerSettings()
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.TextExpressionCompilerSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref> класса."
  syntax:
    content: public TextExpressionCompilerSettings ();
    parameters: []
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Activity
  id: Activity
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: Activity
  nameWithType: TextExpressionCompilerSettings.Activity
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Activity
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Возвращает или задает действие-параметры компилятора."
  syntax:
    content: public System.Activities.Activity Activity { get; set; }
    return:
      type: System.Activities.Activity
      description: "Действие параметров компилятора."
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Activity*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityName
  id: ActivityName
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: ActivityName
  nameWithType: TextExpressionCompilerSettings.ActivityName
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityName
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Возвращает или задает имя действия для параметров компилятора."
  syntax:
    content: public string ActivityName { get; set; }
    return:
      type: System.String
      description: "Имя действия."
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityName*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityNamespace
  id: ActivityNamespace
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: ActivityNamespace
  nameWithType: TextExpressionCompilerSettings.ActivityNamespace
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityNamespace
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Возвращает или задает пространство имен действия."
  syntax:
    content: public string ActivityNamespace { get; set; }
    return:
      type: System.String
      description: "Пространство имен действия."
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityNamespace*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.AlwaysGenerateSource
  id: AlwaysGenerateSource
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: AlwaysGenerateSource
  nameWithType: TextExpressionCompilerSettings.AlwaysGenerateSource
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.AlwaysGenerateSource
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Возвращает или задает значение, указывающее ли параметры компилятора текстового выражения всегда создавать источника."
  syntax:
    content: public bool AlwaysGenerateSource { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Если параметры компилятора текстового выражения всегда создавать источника; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.AlwaysGenerateSource*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ForImplementation
  id: ForImplementation
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: ForImplementation
  nameWithType: TextExpressionCompilerSettings.ForImplementation
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ForImplementation
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Возвращает или задает ли <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref> предназначен для реализации."
  syntax:
    content: public bool ForImplementation { get; set; }
    return:
      type: System.Boolean
      description: "Верно для <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref> предназначен для реализации; в противном случае — значение false."
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ForImplementation*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.GenerateAsPartialClass
  id: GenerateAsPartialClass
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: GenerateAsPartialClass
  nameWithType: TextExpressionCompilerSettings.GenerateAsPartialClass
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.GenerateAsPartialClass
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Возвращает или задает ли <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref> приводит к возникновению ошибки как разделяемый класс."
  syntax:
    content: public bool GenerateAsPartialClass { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>Если <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref> приводит к возникновению ошибки как разделяемый класс; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.GenerateAsPartialClass*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Language
  id: Language
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: Language
  nameWithType: TextExpressionCompilerSettings.Language
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Language
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Возвращает или задает язык, используемый <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref>."
  syntax:
    content: public string Language { get; set; }
    return:
      type: System.String
      description: "Язык, используемый <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref>."
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Language*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.LogSourceGenerationMessage
  id: LogSourceGenerationMessage
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: LogSourceGenerationMessage
  nameWithType: TextExpressionCompilerSettings.LogSourceGenerationMessage
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.LogSourceGenerationMessage
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Возвращает или задает сообщение создания исходного журнала для <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref>."
  syntax:
    content: public Action<string> LogSourceGenerationMessage { get; set; }
    return:
      type: System.Action{System.String}
      description: "Сообщение создания исходного журнала для <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref>."
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.LogSourceGenerationMessage*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.RootNamespace
  id: RootNamespace
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  langs:
  - csharp
  name: RootNamespace
  nameWithType: TextExpressionCompilerSettings.RootNamespace
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.RootNamespace
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Возвращает или задает корневое пространство имен для <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref>."
  syntax:
    content: public string RootNamespace { get; set; }
    return:
      type: System.String
      description: "Корневое пространство имен для <xref href=&quot;System.Activities.XamlIntegration.TextExpressionCompilerSettings&quot;> </xref>."
  overload: System.Activities.XamlIntegration.TextExpressionCompilerSettings.RootNamespace*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.#ctor
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: TextExpressionCompilerSettings()
  nameWithType: TextExpressionCompilerSettings.TextExpressionCompilerSettings()
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.TextExpressionCompilerSettings()
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Activity
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: Activity
  nameWithType: TextExpressionCompilerSettings.Activity
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Activity
- uid: System.Activities.Activity
  parent: System.Activities
  isExternal: false
  name: Activity
  nameWithType: Activity
  fullName: System.Activities.Activity
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityName
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: ActivityName
  nameWithType: TextExpressionCompilerSettings.ActivityName
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityNamespace
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: ActivityNamespace
  nameWithType: TextExpressionCompilerSettings.ActivityNamespace
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityNamespace
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.AlwaysGenerateSource
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: AlwaysGenerateSource
  nameWithType: TextExpressionCompilerSettings.AlwaysGenerateSource
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.AlwaysGenerateSource
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ForImplementation
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: ForImplementation
  nameWithType: TextExpressionCompilerSettings.ForImplementation
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ForImplementation
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.GenerateAsPartialClass
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: GenerateAsPartialClass
  nameWithType: TextExpressionCompilerSettings.GenerateAsPartialClass
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.GenerateAsPartialClass
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Language
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: Language
  nameWithType: TextExpressionCompilerSettings.Language
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Language
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.LogSourceGenerationMessage
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: LogSourceGenerationMessage
  nameWithType: TextExpressionCompilerSettings.LogSourceGenerationMessage
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.LogSourceGenerationMessage
- uid: System.Action{System.String}
  parent: System
  isExternal: true
  name: Action<String>
  nameWithType: Action<String>
  fullName: System.Action<System.String>
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: Action<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.RootNamespace
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: RootNamespace
  nameWithType: TextExpressionCompilerSettings.RootNamespace
  fullName: System.Activities.XamlIntegration.TextExpressionCompilerSettings.RootNamespace
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.#ctor*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: TextExpressionCompilerSettings
  nameWithType: TextExpressionCompilerSettings.TextExpressionCompilerSettings
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Activity*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: Activity
  nameWithType: TextExpressionCompilerSettings.Activity
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityName*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: ActivityName
  nameWithType: TextExpressionCompilerSettings.ActivityName
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ActivityNamespace*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: ActivityNamespace
  nameWithType: TextExpressionCompilerSettings.ActivityNamespace
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.AlwaysGenerateSource*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: AlwaysGenerateSource
  nameWithType: TextExpressionCompilerSettings.AlwaysGenerateSource
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.ForImplementation*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: ForImplementation
  nameWithType: TextExpressionCompilerSettings.ForImplementation
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.GenerateAsPartialClass*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: GenerateAsPartialClass
  nameWithType: TextExpressionCompilerSettings.GenerateAsPartialClass
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.Language*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: Language
  nameWithType: TextExpressionCompilerSettings.Language
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.LogSourceGenerationMessage*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: LogSourceGenerationMessage
  nameWithType: TextExpressionCompilerSettings.LogSourceGenerationMessage
- uid: System.Activities.XamlIntegration.TextExpressionCompilerSettings.RootNamespace*
  parent: System.Activities.XamlIntegration.TextExpressionCompilerSettings
  isExternal: false
  name: RootNamespace
  nameWithType: TextExpressionCompilerSettings.RootNamespace
