### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.UserMapPath
  id: UserMapPath
  children:
  - System.Web.Configuration.UserMapPath.#ctor(System.Configuration.ConfigurationFileMap)
  - System.Web.Configuration.UserMapPath.GetAppPathForPath(System.String,System.String)
  - System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  - System.Web.Configuration.UserMapPath.GetMachineConfigFilename
  - System.Web.Configuration.UserMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  - System.Web.Configuration.UserMapPath.GetRootWebConfigFilename
  - System.Web.Configuration.UserMapPath.MapPath(System.String,System.String)
  - System.Web.Configuration.UserMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  langs:
  - csharp
  name: UserMapPath
  nameWithType: UserMapPath
  fullName: System.Web.Configuration.UserMapPath
  type: Class
  summary: "Сопоставляет физические пути виртуального пути к файлам конфигурации."
  syntax:
    content: 'public class UserMapPath : System.Web.Configuration.IConfigMapPath'
  inheritance:
  - System.Object
  implements:
  - System.Web.Configuration.IConfigMapPath
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.#ctor(System.Configuration.ConfigurationFileMap)
  id: '#ctor(System.Configuration.ConfigurationFileMap)'
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: UserMapPath(ConfigurationFileMap)
  nameWithType: UserMapPath.UserMapPath(ConfigurationFileMap)
  fullName: System.Web.Configuration.UserMapPath.UserMapPath(ConfigurationFileMap)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <xref href=&quot;System.Web.Configuration.UserMapPath&quot;></xref> class."
  syntax:
    content: public UserMapPath (System.Configuration.ConfigurationFileMap fileMap);
    parameters:
    - id: fileMap
      type: System.Configuration.ConfigurationFileMap
      description: "Сопоставление файла конфигурации для файла конфигурации компьютера."
  overload: System.Web.Configuration.UserMapPath.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetAppPathForPath(System.String,System.String)
  id: GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetAppPathForPath(String,String)
  nameWithType: UserMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.UserMapPath.GetAppPathForPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Возвращает имя виртуального каталога, который связан с конкретным сайтом."
  syntax:
    content: public string GetAppPathForPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "Уникальный идентификатор для сайта."
    - id: path
      type: System.String
      description: "URL-адрес, связанный с узлом."
    return:
      type: System.String
      description: "<code> siteID </code> Значение должно быть уникальным. <code> siteID </code> Значение позволяет различать узлы с одинаковыми именами."
  overload: System.Web.Configuration.UserMapPath.GetAppPathForPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  id: GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: UserMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Заполняет имя узла по умолчанию и идентификатор узла."
  syntax:
    content: public void GetDefaultSiteNameAndID (out string siteName, out string siteID);
    parameters:
    - id: siteName
      type: System.String
      description: "Имя узла по умолчанию."
    - id: siteID
      type: System.String
      description: "Уникальный идентификатор для сайта."
  overload: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetMachineConfigFilename
  id: GetMachineConfigFilename
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetMachineConfigFilename()
  nameWithType: UserMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.UserMapPath.GetMachineConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Возвращает имя файла конфигурации компьютера."
  syntax:
    content: public string GetMachineConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "Имя файла конфигурации компьютера."
  overload: System.Web.Configuration.UserMapPath.GetMachineConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  id: GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: UserMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.UserMapPath.GetPathConfigFilename(String,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Заполняет каталог и имя файла конфигурации на основе идентификатора узла и путь к сайту."
  syntax:
    content: public void GetPathConfigFilename (string siteID, string path, out string directory, out string baseName);
    parameters:
    - id: siteID
      type: System.String
      description: "Уникальный идентификатор для сайта."
    - id: path
      type: System.String
      description: "URL-адрес, связанный с узлом."
    - id: directory
      type: System.String
      description: "Физический путь файла конфигурации."
    - id: baseName
      type: System.String
      description: "Имя файла конфигурации."
  overload: System.Web.Configuration.UserMapPath.GetPathConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename
  id: GetRootWebConfigFilename
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetRootWebConfigFilename()
  nameWithType: UserMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Возвращает физический путь файла конфигурации, находящийся в корневой папке веб-приложения."
  syntax:
    content: public string GetRootWebConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "Физический путь в файле Web.config в корень веб-приложения."
  overload: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.MapPath(System.String,System.String)
  id: MapPath(System.String,System.String)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: MapPath(String,String)
  nameWithType: UserMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.UserMapPath.MapPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Возвращает физический путь на основе идентификатора узла и URL-адрес, связанный с узлом."
  syntax:
    content: public string MapPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "Уникальный идентификатор для сайта."
    - id: path
      type: System.String
      description: "URL-адрес, связанный с узлом."
    return:
      type: System.String
      description: "Физический путь к узлу."
  overload: System.Web.Configuration.UserMapPath.MapPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  id: ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: ResolveSiteArgument(String,String,String)
  nameWithType: UserMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.UserMapPath.ResolveSiteArgument(String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Заполняет имя узла и идентификатор узла, на основе значения аргумента узла."
  remarks: "Если `siteArgument` — `null`, совпадает с именем узла по умолчанию или равен идентификатору узла по умолчанию, `siteName` и `siteID` значения заполняются значениями узла по умолчанию."
  syntax:
    content: public void ResolveSiteArgument (string siteArgument, out string siteName, out string siteID);
    parameters:
    - id: siteArgument
      type: System.String
      description: "Имя узла и идентификатор узла."
    - id: siteName
      type: System.String
      description: "Имя узла по умолчанию."
    - id: siteID
      type: System.String
      description: "Уникальный идентификатор для сайта."
  overload: System.Web.Configuration.UserMapPath.ResolveSiteArgument*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.UserMapPath.#ctor(System.Configuration.ConfigurationFileMap)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: UserMapPath(ConfigurationFileMap)
  nameWithType: UserMapPath.UserMapPath(ConfigurationFileMap)
  fullName: System.Web.Configuration.UserMapPath.UserMapPath(ConfigurationFileMap)
- uid: System.Configuration.ConfigurationFileMap
  parent: System.Configuration
  isExternal: false
  name: ConfigurationFileMap
  nameWithType: ConfigurationFileMap
  fullName: System.Configuration.ConfigurationFileMap
- uid: System.Web.Configuration.UserMapPath.GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetAppPathForPath(String,String)
  nameWithType: UserMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.UserMapPath.GetAppPathForPath(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: UserMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(String,String)
- uid: System.Web.Configuration.UserMapPath.GetMachineConfigFilename
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetMachineConfigFilename()
  nameWithType: UserMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.UserMapPath.GetMachineConfigFilename()
- uid: System.Web.Configuration.UserMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: UserMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.UserMapPath.GetPathConfigFilename(String,String,String,String)
- uid: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetRootWebConfigFilename()
  nameWithType: UserMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename()
- uid: System.Web.Configuration.UserMapPath.MapPath(System.String,System.String)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: MapPath(String,String)
  nameWithType: UserMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.UserMapPath.MapPath(String,String)
- uid: System.Web.Configuration.UserMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: ResolveSiteArgument(String,String,String)
  nameWithType: UserMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.UserMapPath.ResolveSiteArgument(String,String,String)
- uid: System.Web.Configuration.UserMapPath.#ctor*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: UserMapPath
  nameWithType: UserMapPath.UserMapPath
- uid: System.Web.Configuration.UserMapPath.GetAppPathForPath*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetAppPathForPath
  nameWithType: UserMapPath.GetAppPathForPath
- uid: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID
  nameWithType: UserMapPath.GetDefaultSiteNameAndID
- uid: System.Web.Configuration.UserMapPath.GetMachineConfigFilename*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetMachineConfigFilename
  nameWithType: UserMapPath.GetMachineConfigFilename
- uid: System.Web.Configuration.UserMapPath.GetPathConfigFilename*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetPathConfigFilename
  nameWithType: UserMapPath.GetPathConfigFilename
- uid: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetRootWebConfigFilename
  nameWithType: UserMapPath.GetRootWebConfigFilename
- uid: System.Web.Configuration.UserMapPath.MapPath*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: MapPath
  nameWithType: UserMapPath.MapPath
- uid: System.Web.Configuration.UserMapPath.ResolveSiteArgument*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: ResolveSiteArgument
  nameWithType: UserMapPath.ResolveSiteArgument
