### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigurationManagerInternal
  id: IConfigurationManagerInternal
  children:
  - System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  - System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  - System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  - System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  - System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  langs:
  - csharp
  name: IConfigurationManagerInternal
  nameWithType: IConfigurationManagerInternal
  fullName: System.Configuration.Internal.IConfigurationManagerInternal
  type: Interface
  summary: "Определяет интерфейс, используемый платформой .NET Framework, для инициализации свойств конфигурации."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IConfigurationManagerInternal
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  id: ApplicationConfigUri
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ApplicationConfigUri
  nameWithType: IConfigurationManagerInternal.ApplicationConfigUri
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает имя файла конфигурации, относящиеся к пути приложения."
  syntax:
    content: public string ApplicationConfigUri { get; }
    return:
      type: System.String
      description: "Строковое значение, представляющее имя файла конфигурации."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  id: ExeLocalConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeLocalConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает локальный каталог конфигурации приложения, основанного на сборке записей."
  syntax:
    content: public string ExeLocalConfigDirectory { get; }
    return:
      type: System.String
      description: "Строка, представляющая локальный каталог конфигурации."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  id: ExeLocalConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeLocalConfigPath
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает путь локальной конфигурации приложения, основанного на сборке записей."
  syntax:
    content: public string ExeLocalConfigPath { get; }
    return:
      type: System.String
      description: "Строковое значение, представляющее путь локальной конфигурации приложения."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  id: ExeProductName
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeProductName
  nameWithType: IConfigurationManagerInternal.ExeProductName
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает имя продукта приложения, основанного на сборке записей."
  syntax:
    content: public string ExeProductName { get; }
    return:
      type: System.String
      description: "Строковое значение, представляющее имя продукта приложения."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  id: ExeProductVersion
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeProductVersion
  nameWithType: IConfigurationManagerInternal.ExeProductVersion
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает версию продукта приложения, основанного на сборке записей."
  syntax:
    content: public string ExeProductVersion { get; }
    return:
      type: System.String
      description: "Строковое значение, представляющее версию продукта приложения."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  id: ExeRoamingConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeRoamingConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает перемещаемый каталог конфигурации приложения, основанного на сборке записей."
  syntax:
    content: public string ExeRoamingConfigDirectory { get; }
    return:
      type: System.String
      description: "Строковое значение, представляющее перемещаемый каталог конфигурации приложения."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  id: ExeRoamingConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeRoamingConfigPath
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает путь перемещаемой пользовательской конфигурации на основании запись сборки приложения."
  syntax:
    content: public string ExeRoamingConfigPath { get; }
    return:
      type: System.String
      description: "Строковое значение, представляющее путь перемещаемой пользовательской конфигурации."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  id: MachineConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: MachineConfigPath
  nameWithType: IConfigurationManagerInternal.MachineConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает путь к конфигурации для файла Machine.config."
  syntax:
    content: public string MachineConfigPath { get; }
    return:
      type: System.String
      description: "Строковое значение, представляющее путь к файлу Machine.config."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  id: SetConfigurationSystemInProgress
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: SetConfigurationSystemInProgress
  nameWithType: IConfigurationManagerInternal.SetConfigurationSystemInProgress
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Получает значение, представляющее состояние системы конфигурации."
  remarks: "Свойство SetConfigurationSystemInProgress используется <xref:System.Diagnostics>при инициализации конфигурации.</xref:System.Diagnostics>"
  syntax:
    content: public bool SetConfigurationSystemInProgress { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Если система конфигурации в процессе инициализации; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  id: SupportsUserConfig
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: SupportsUserConfig
  nameWithType: IConfigurationManagerInternal.SupportsUserConfig
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает значение, указывающее, поддерживаются ли параметры пользовательской конфигурации."
  syntax:
    content: public bool SupportsUserConfig { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Если система конфигурации поддерживает параметры пользовательской конфигурации; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  id: UserConfigFilename
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: UserConfigFilename
  nameWithType: IConfigurationManagerInternal.UserConfigFilename
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Возвращает имя файла, используемого для хранения параметров конфигурации пользователя."
  syntax:
    content: public string UserConfigFilename { get; }
    return:
      type: System.String
      description: "Строка, указывающая имя файла, используемого для хранения пользовательской конфигурации."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ApplicationConfigUri
  nameWithType: IConfigurationManagerInternal.ApplicationConfigUri
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigPath
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductName
  nameWithType: IConfigurationManagerInternal.ExeProductName
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductVersion
  nameWithType: IConfigurationManagerInternal.ExeProductVersion
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigPath
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: MachineConfigPath
  nameWithType: IConfigurationManagerInternal.MachineConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SetConfigurationSystemInProgress
  nameWithType: IConfigurationManagerInternal.SetConfigurationSystemInProgress
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IConfigurationManagerInternal.SupportsUserConfig
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
- uid: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: UserConfigFilename
  nameWithType: IConfigurationManagerInternal.UserConfigFilename
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ApplicationConfigUri
  nameWithType: IConfigurationManagerInternal.ApplicationConfigUri
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigPath
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductName
  nameWithType: IConfigurationManagerInternal.ExeProductName
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductVersion
  nameWithType: IConfigurationManagerInternal.ExeProductVersion
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigPath
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: MachineConfigPath
  nameWithType: IConfigurationManagerInternal.MachineConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SetConfigurationSystemInProgress
  nameWithType: IConfigurationManagerInternal.SetConfigurationSystemInProgress
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IConfigurationManagerInternal.SupportsUserConfig
- uid: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: UserConfigFilename
  nameWithType: IConfigurationManagerInternal.UserConfigFilename
