### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FolderLevelBuildProvider
  id: FolderLevelBuildProvider
  children:
  - System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  - System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  - System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  - System.Web.Configuration.FolderLevelBuildProvider.Name
  - System.Web.Configuration.FolderLevelBuildProvider.Properties
  - System.Web.Configuration.FolderLevelBuildProvider.Type
  langs:
  - csharp
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider
  fullName: System.Web.Configuration.FolderLevelBuildProvider
  type: Class
  summary: "Представляет параметры конфигурации, которые позволяют использовать <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> класса для конкретной папки."
  remarks: "Среды разработки ASP.NET использует FolderLevelBuildProvider объекты для создания исходного кода для различных типах файлов и подкаталогов, в приложении. Классы, производные от класса FolderLevelBuildProvider создать исходный код для папок, таких как Bin App_GlobalResources, App_LocalResources, App_WebReferences, App_Browsers, темы и другие пользовательские папки. Как правило не создается экземпляр класса FolderLevelBuildProvider напрямую. Вместо этого при реализации класса, производного от <xref:System.Web.Compilation.BuildProvider>и применить <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>класса к нему, а затем настройте производный класс для использования в среде построения ASP.NET.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute> </xref:System.Web.Compilation.BuildProvider> <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>Класс предназначен для папок, а не файлы.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>       Используйте экземпляры класса FolderLevelBuildProvider вместе с <xref:System.Web.Compilation.AssemblyBuilder>объектов для построения одного или нескольких файлов в скомпилированной сборке.</xref:System.Web.Compilation.AssemblyBuilder> Экземпляр FolderLevelBuildProvider создает исходный код на соответствующем языке для отдельных файлов и <xref:System.Web.Compilation.AssemblyBuilder>объект сборки исходного кода, представленные каждым экземпляром FolderLevelBuildProvider в одну сборку.</xref:System.Web.Compilation.AssemblyBuilder>       Класс FolderLevelBuildProvider, указанный в `configuration` раздел файла Web.config."
  example:
  - "The following example shows how to add a build provider named `BuildProvider1` to the Web.config file.  \n  \n```  \n<compilation>  \n  <folderLevelBuildProviders>  \n    <add type=\"BuildProvider1, Assembly1,Version=1.0.0.0,    \n        PublicKeyToken=xxxxx\"/>  \n  </folderLevelBuildProviders>  \n</compilation>  \n```"
  syntax:
    content: 'public sealed class FolderLevelBuildProvider : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> , используя идентификатор и полное доменное имя."
  syntax:
    content: public FolderLevelBuildProvider (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "Идентификатор для <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> для использования."
    - id: type
      type: System.String
      description: "Полное имя <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> для использования."
  overload: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Возвращает значение, указывающее, равен ли указанный объект текущему <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> объекта."
  syntax:
    content: public override bool Equals (object provider);
    parameters:
    - id: provider
      type: System.Object
      description: "Объект поставщика построения для сравнения."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Объект поставщика построения на уровне указанной папки равен ли текущий объект; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Создает хэш-код для <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> объекта."
  remarks: "Этот метод создает целое число, можно использовать для идентификации объекта поставщика построения уровня папки. Этот метод наследуется от <xref:System.Object.GetHashCode%2A>метод.</xref:System.Object.GetHashCode%2A> <xref:System.Object.GetHashCode%2A>Метод подходит для использования в алгоритмах и структурах данных, таких как хэш-таблицу хеширования.</xref:System.Object.GetHashCode%2A>"
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Хэш-код для <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> объекта."
  overload: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  id: Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Возвращает или задает имя <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> объекта."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Имя объекта поставщика построения."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  id: Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Для добавления."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  id: Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Получает или задает полное имя класса поставщика построения."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Полное имя класса поставщика построения."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals
  nameWithType: FolderLevelBuildProvider.Equals
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode
  nameWithType: FolderLevelBuildProvider.GetHashCode
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
