### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventArgs
  id: SettingChangingEventArgs
  children:
  - System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  - System.Configuration.SettingChangingEventArgs.NewValue
  - System.Configuration.SettingChangingEventArgs.SettingClass
  - System.Configuration.SettingChangingEventArgs.SettingKey
  - System.Configuration.SettingChangingEventArgs.SettingName
  langs:
  - csharp
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs
  fullName: System.Configuration.SettingChangingEventArgs
  type: Class
  summary: "Предоставляет данные для <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> событий."
  remarks: "Класс SettingChangingEventArgs предоставляет данные для <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>событие, которое указывает, что значение свойства параметров приложения будет изменена.</xref:System.Configuration.ApplicationSettingsBase.SettingChanging> Наиболее распространенный источник для этого события является `get` доступа <xref:System.Configuration.ApplicationSettingsBase.Item%2A>метода в <xref:System.Configuration.ApplicationSettingsBase>классе.</xref:System.Configuration.ApplicationSettingsBase> </xref:System.Configuration.ApplicationSettingsBase.Item%2A>       Поскольку производными SettingChangingEventArgs <xref:System.ComponentModel.CancelEventArgs>, обработчик имеет возможность отмены операции записи.</xref:System.ComponentModel.CancelEventArgs>"
  syntax:
    content: 'public class SettingChangingEventArgs : System.ComponentModel.CancelEventArgs'
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  id: '#ctor(System.String,System.String,System.String,System.Object,System.Boolean)'
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Инициализирует новый экземпляр класса <xref href=&quot;System.Configuration.SettingChangingEventArgs&quot;> </xref> класса."
  remarks: "Конструктор SettingChangingEventArgs просто присваивает значения параметров, соответствующие свойства в <xref:System.Configuration.SettingChangingEventArgs>классе.</xref:System.Configuration.SettingChangingEventArgs>"
  syntax:
    content: public SettingChangingEventArgs (string settingName, string settingClass, string settingKey, object newValue, bool cancel);
    parameters:
    - id: settingName
      type: System.String
      description: "Объект <xref:System.String>содержит имя параметра приложения.</xref:System.String>"
    - id: settingClass
      type: System.String
      description: "Объект <xref:System.String>содержащий описание категории параметра.</xref:System.String> Часто этот параметр будет присвоено имя группы параметров приложения."
    - id: settingKey
      type: System.String
      description: "Объект <xref:System.String>содержит ключ параметров приложения.</xref:System.String>"
    - id: newValue
      type: System.Object
      description: "<xref:System.Object>, Содержащий новое значение, присваиваемое свойству параметров приложения.</xref:System.Object>"
    - id: cancel
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Чтобы отменить событие; в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.SettingChangingEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  id: NewValue
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Возвращает новое значение, присваиваемое свойства параметров приложения."
  remarks: "Фактический тип новое значение свойства должно быть совместима с устанавливаемое свойство параметров. Последний доступен хотя <xref:System.Configuration.SettingsProperty.PropertyType%2A>Свойства <xref:System.Configuration.SettingsProperty>класса.</xref:System.Configuration.SettingsProperty> </xref:System.Configuration.SettingsProperty.PropertyType%2A>"
  syntax:
    content: public object NewValue { get; }
    return:
      type: System.Object
      description: "<xref:System.Object>, Содержащий новое значение, присваиваемое свойству параметров приложения.</xref:System.Object>"
  overload: System.Configuration.SettingChangingEventArgs.NewValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  id: SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Возвращает категорию свойства параметров приложения."
  remarks: "Все параметры приложения принадлежат группе параметров приложения. Имя группы может быть явно предоставленный декорирования класса <xref:System.Configuration.SettingsGroupNameAttribute>в противном случае создается с использованием имени класса-оболочки параметров.</xref:System.Configuration.SettingsGroupNameAttribute>"
  syntax:
    content: public string SettingClass { get; }
    return:
      type: System.String
      description: "Объект <xref:System.String>содержащий описание категории параметра.</xref:System.String> Как правило этот параметр имеет значение имени группы параметров приложения."
  overload: System.Configuration.SettingChangingEventArgs.SettingClass*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  id: SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Возвращает ключ параметров приложения, связанное со свойством."
  remarks: "Каждый класс-оболочка параметров, производный от <xref:System.Configuration.ApplicationSettingsBase>, имеет связанный ключ параметров, который является строкой, которая позволяет различать разные экземпляры одной программы-оболочки в одном приложении.</xref:System.Configuration.ApplicationSettingsBase> Так как каждый класс-оболочка определяет набор свойств, которые представляют параметры приложения, ключ параметров точно так же может помочь устранить неоднозначность их использования."
  syntax:
    content: public string SettingKey { get; }
    return:
      type: System.String
      description: "Объект <xref:System.String>содержит ключ параметров приложения.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingKey*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  id: SettingName
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Возвращает имя параметра приложения, связанное со свойством параметров приложения."
  remarks: "Обычно параметры класс-оболочку, производный от <xref:System.Configuration.ApplicationSettingsBase>, будут созданы таким образом, имя свойства параметров приложения будет таким же, как его параметр связанного приложения.</xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: public string SettingName { get; }
    return:
      type: System.String
      description: "Объект <xref:System.String>содержит имя параметра приложения.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
- uid: System.Configuration.SettingChangingEventArgs.#ctor*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs
- uid: System.Configuration.SettingChangingEventArgs.NewValue*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
