### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer
  id: IRemoteWebConfigurationHostServer
  children:
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  langs:
  - csharp
  name: IRemoteWebConfigurationHostServer
  nameWithType: IRemoteWebConfigurationHostServer
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer
  type: Interface
  summary: "Используется внутренним образом для поддержки удаленного доступа к данным конфигурации."
  remarks: "Базовый класс, из которого <xref:System.Web.Configuration.RemoteWebConfigurationHostServer>расширяет.</xref:System.Web.Configuration.RemoteWebConfigurationHostServer>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Runtime.InteropServices.Guid("A99B591A-23C6-4238-8452-C7B0E895063D")]

      public interface IRemoteWebConfigurationHostServer
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  id: DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Условно зашифровывает или расшифровывает значение строки, на который указывает <code> xmlString </code> параметра."
  syntax:
    content: public string DoEncryptOrDecrypt (bool doEncrypt, string xmlString, string protectionProviderName, string protectionProviderType, string[] parameterKeys, string[] parameterValues);
    parameters:
    - id: doEncrypt
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>для шифрования; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> для расшифровки."
    - id: xmlString
      type: System.String
      description: "XML для шифрования и расшифровки."
    - id: protectionProviderName
      type: System.String
      description: "Поставщик, используемый для защиты данных конфигурации."
    - id: protectionProviderType
      type: System.String
      description: "<xref:System.Type>Поставщика защиты.</xref:System.Type>"
    - id: parameterKeys
      type: System.String[]
      description: "Ключи дополнительных параметров для поставщика защиты."
    - id: parameterValues
      type: System.String[]
      description: "Значения необязательных параметров для поставщика защиты."
    return:
      type: System.String
      description: "Строка, содержащая зашифрованные или расшифрованные значения из <code> xmlString </code>."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  id: GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetData(String,Boolean,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Используется внутренним образом для поддержки удаленного доступа к данным конфигурации."
  syntax:
    content: public byte[] GetData (string fileName, bool getReadTimeOnly, out long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Путь к файлу конфигурации удаленный доступ к."
    - id: getReadTimeOnly
      type: System.Boolean
      description: "Логическое значение, указывающее ли только `readTime` возвращается."
    - id: readTime
      type: System.Int64
      description: "Время последнего доступа к файлу."
    return:
      type: System.Byte[]
      description: "<xref uid=&quot;langword_csharp_array&quot; name=&quot;array&quot; href=&quot;&quot;> </xref> 8-разрядных целых чисел без знака (в байтах) с данными конфигурации."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  id: GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Возвращает сведения о файле конфигурации."
  syntax:
    content: public void GetFileDetails (string name, out bool exists, out long size, out long createDate, out long lastWriteDate);
    parameters:
    - id: name
      type: System.String
      description: "Имя файла."
    - id: exists
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Если он существует. в противном случае <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: size
      type: System.Int64
      description: "Размер файла."
    - id: createDate
      type: System.Int64
      description: "Дата создания файла."
    - id: lastWriteDate
      type: System.Int64
      description: "Дата последней записи файла."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  id: GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Используется внутренним образом для поддержки удаленного доступа к данным конфигурации."
  syntax:
    content: public string GetFilePaths (int webLevel, string path, string site, string locationSubPath);
    parameters:
    - id: webLevel
      type: System.Int32
      description: "Уровень в файле конфигурации."
    - id: path
      type: System.String
      description: "Путь к файлу конфигурации удаленный доступ к."
    - id: site
      type: System.String
      description: "Путь к удаленному компьютеру."
    - id: locationSubPath
      type: System.String
      description: "Вложенный путь расположения файла конфигурации."
    return:
      type: System.String
      description: "Объединенная строка, представляющая путь к файлу в файле конфигурации."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  id: WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Используется внутренним образом для поддержки удаленного доступа к данным конфигурации."
  syntax:
    content: public void WriteData (string fileName, string templateFileName, byte[] data, ref long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Путь к файлу конфигурации удаленный доступ к."
    - id: templateFileName
      type: System.String
      description: "Повторяющиеся атрибуты файла из файла."
    - id: data
      type: System.Byte[]
      description: "Записываемые данные."
    - id: readTime
      type: System.Int64
      description: "Время последнего доступа к файлу."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetData(String,Boolean,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetData
  nameWithType: IRemoteWebConfigurationHostServer.GetData
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData
  nameWithType: IRemoteWebConfigurationHostServer.WriteData
