### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfiguration
  id: ProtectedConfiguration
  children:
  - System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  - System.Configuration.ProtectedConfiguration.DefaultProvider
  - System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  - System.Configuration.ProtectedConfiguration.Providers
  - System.Configuration.ProtectedConfiguration.RsaProviderName
  langs:
  - csharp
  name: ProtectedConfiguration
  nameWithType: ProtectedConfiguration
  fullName: System.Configuration.ProtectedConfiguration
  type: Class
  summary: "Предоставляет доступ к защищенной конфигурации поставщиков для файла конфигурации текущего приложения."
  remarks: "Класс ProtectedConfiguration позволяет получить сведения о поставщиках, можно защитить конфиденциальные данные конфигурации. Как правило, используется стандартные поставщики, но можно также создать настраиваемые поставщики путем наследования от <xref:System.Configuration.ProtectedConfigurationProvider>класса.</xref:System.Configuration.ProtectedConfigurationProvider>       Дополнительные сведения о защищенной конфигурации см. в разделе [шифрование конфигурации сведения с помощью защищенной конфигурации](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following example shows how to use the ProtectedConfiguration class to retrieve a collection of protected-configuration providers and discover their provider name, RSA provider name, and section names.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#1](~/add/codesnippet/csharp/t-system.configuration.p_4_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#1](~/add/codesnippet/visualbasic/t-system.configuration.p_4_1.vb)]"
  syntax:
    content: public static class ProtectedConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  id: DataProtectionProviderName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: DataProtectionProviderName
  nameWithType: ProtectedConfiguration.DataProtectionProviderName
  fullName: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Имя поставщика защищенных данных."
  remarks: "Это постоянное строковую переменную, которая содержит имя поставщика защиты данных предоставляется с системой для защиты раздела конфигурации."
  example:
  - "The following example shows how to use the DataProtectionProviderName property to retrieve the name of the current data-protection provider.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#4](~/add/codesnippet/csharp/f-system.configuration.p_2_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#4](~/add/codesnippet/visualbasic/f-system.configuration.p_2_1.vb)]"
  syntax:
    content: public const string DataProtectionProviderName;
    return:
      type: System.String
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider
  id: DefaultProvider
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
  fullName: System.Configuration.ProtectedConfiguration.DefaultProvider
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Получает имя поставщика защищенной конфигурации по умолчанию."
  remarks: "Поставщик по умолчанию определяется по `defaultProvider` атрибут `<configProtectedData>` элемента файла конфигурации. Значение должно соответствовать имени одного из поставщиков, добавленных в `<providers>` подразделе `<configProtectedData>` раздела. `<configProtectedData>` Разделе можно получить через экземпляр <xref:System.Configuration.ProtectedConfigurationSection>класса.</xref:System.Configuration.ProtectedConfigurationSection>"
  syntax:
    content: public static string DefaultProvider { get; }
    return:
      type: System.String
      description: "Имя поставщика защищенной конфигурации по умолчанию."
  overload: System.Configuration.ProtectedConfiguration.DefaultProvider*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  id: ProtectedDataSectionName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: ProtectedDataSectionName
  nameWithType: ProtectedConfiguration.ProtectedDataSectionName
  fullName: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Имя раздела защищенных данных."
  remarks: "Это постоянное строковую переменную, которая содержит имя раздела защищенных данных."
  example:
  - "The following example shows how to use the ProtectedDataSectionName property to retrieve the name of a protected data section.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#6](~/add/codesnippet/csharp/f-system.configuration.p_0_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#6](~/add/codesnippet/visualbasic/f-system.configuration.p_0_1.vb)]"
  syntax:
    content: public const string ProtectedDataSectionName;
    return:
      type: System.String
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.Providers
  id: Providers
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
  fullName: System.Configuration.ProtectedConfiguration.Providers
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Возвращает коллекцию установленных поставщиков защищенной конфигурации."
  remarks: ''
  example:
  - "The following example shows how to use the Providers property to retrieve the collection of installed <xref:System.Configuration.ProtectedConfigurationProvider> objects.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#3](~/add/codesnippet/csharp/p-system.configuration.p_16_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#3](~/add/codesnippet/visualbasic/p-system.configuration.p_16_1.vb)]"
  syntax:
    content: public static System.Configuration.ProtectedConfigurationProviderCollection Providers { get; }
    return:
      type: System.Configuration.ProtectedConfigurationProviderCollection
      description: "Объект <xref href=&quot;System.Configuration.ProtectedConfigurationProviderCollection&quot;> </xref> установлен коллекцию <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> объектов."
  overload: System.Configuration.ProtectedConfiguration.Providers*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.RsaProviderName
  id: RsaProviderName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: RsaProviderName
  nameWithType: ProtectedConfiguration.RsaProviderName
  fullName: System.Configuration.ProtectedConfiguration.RsaProviderName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Имя поставщика RSA."
  remarks: "Это постоянное строковую переменную, которая содержит имя поставщика RSA, предоставляемого системой для защиты раздела конфигурации."
  example:
  - "The following example shows how to use the RsaProviderName property to retrieve the name of the current RSA provider.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#5](~/add/codesnippet/csharp/f-system.configuration.p_1_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#5](~/add/codesnippet/visualbasic/f-system.configuration.p_1_1.vb)]"
  syntax:
    content: public const string RsaProviderName;
    return:
      type: System.String
      description: "Для добавления."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DataProtectionProviderName
  nameWithType: ProtectedConfiguration.DataProtectionProviderName
  fullName: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
  fullName: System.Configuration.ProtectedConfiguration.DefaultProvider
- uid: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: ProtectedDataSectionName
  nameWithType: ProtectedConfiguration.ProtectedDataSectionName
  fullName: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
- uid: System.Configuration.ProtectedConfiguration.Providers
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
  fullName: System.Configuration.ProtectedConfiguration.Providers
- uid: System.Configuration.ProtectedConfigurationProviderCollection
  parent: System.Configuration
  isExternal: false
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection
  fullName: System.Configuration.ProtectedConfigurationProviderCollection
- uid: System.Configuration.ProtectedConfiguration.RsaProviderName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: RsaProviderName
  nameWithType: ProtectedConfiguration.RsaProviderName
  fullName: System.Configuration.ProtectedConfiguration.RsaProviderName
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider*
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
- uid: System.Configuration.ProtectedConfiguration.Providers*
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
