### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventHandler
  id: SettingsLoadedEventHandler
  langs:
  - csharp
  name: SettingsLoadedEventHandler
  nameWithType: SettingsLoadedEventHandler
  fullName: System.Configuration.SettingsLoadedEventHandler
  type: Delegate
  summary: "Представляет метод, обрабатывающий <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;> </xref> событий."
  remarks: "<xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>Событие происходит, когда параметры извлекаются из поставщика.</xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded> Это событие вызывается один раз для каждого поставщика."
  syntax:
    content: public delegate void SettingsLoadedEventHandler(object sender, SettingsLoadedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
