### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.IApplicationHost
  id: IApplicationHost
  children:
  - System.Web.Hosting.IApplicationHost.GetConfigMapPathFactory
  - System.Web.Hosting.IApplicationHost.GetConfigToken
  - System.Web.Hosting.IApplicationHost.GetPhysicalPath
  - System.Web.Hosting.IApplicationHost.GetSiteID
  - System.Web.Hosting.IApplicationHost.GetSiteName
  - System.Web.Hosting.IApplicationHost.GetVirtualPath
  - System.Web.Hosting.IApplicationHost.MessageReceived
  langs:
  - csharp
  name: IApplicationHost
  nameWithType: IApplicationHost
  fullName: System.Web.Hosting.IApplicationHost
  type: Interface
  summary: "Извлекает сведения об узле приложения."
  remarks: "IApplicationHost впервые появился в [!INCLUDE[net_v35_long](~/add/includes/ajax-current-ext-md.md)]. Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public interface IApplicationHost
  implements: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationHost.GetConfigMapPathFactory
  id: GetConfigMapPathFactory
  parent: System.Web.Hosting.IApplicationHost
  langs:
  - csharp
  name: GetConfigMapPathFactory()
  nameWithType: IApplicationHost.GetConfigMapPathFactory()
  fullName: System.Web.Hosting.IApplicationHost.GetConfigMapPathFactory()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Обеспечивает создание <xref href=&quot;System.Web.Configuration.IConfigMapPath&quot;> </xref> интерфейса в целевом домене приложения."
  remarks: "GetConfigMapPathFactory впервые появился в [!INCLUDE[net_v35_long](~/add/includes/ajax-current-ext-md.md)]. Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public System.Web.Configuration.IConfigMapPathFactory GetConfigMapPathFactory ();
    parameters: []
    return:
      type: System.Web.Configuration.IConfigMapPathFactory
      description: "Объект, используемый для сопоставления виртуального и физического пути файла конфигурации."
  overload: System.Web.Hosting.IApplicationHost.GetConfigMapPathFactory*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationHost.GetConfigToken
  id: GetConfigToken
  parent: System.Web.Hosting.IApplicationHost
  langs:
  - csharp
  name: GetConfigToken()
  nameWithType: IApplicationHost.GetConfigToken()
  fullName: System.Web.Hosting.IApplicationHost.GetConfigToken()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Получает маркер для файла конфигурации (.config) ведущего приложения."
  remarks: "GetConfigToken впервые появился в [!INCLUDE[net_v35_long](~/add/includes/ajax-current-ext-md.md)]. Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public IntPtr GetConfigToken ();
    parameters: []
    return:
      type: System.IntPtr
      description: "Дескриптор Windows, содержащий токен безопасности Windows для корневого каталога приложения. Маркер можно использовать для открытия и чтения файла конфигурации приложения."
  overload: System.Web.Hosting.IApplicationHost.GetConfigToken*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationHost.GetPhysicalPath
  id: GetPhysicalPath
  parent: System.Web.Hosting.IApplicationHost
  langs:
  - csharp
  name: GetPhysicalPath()
  nameWithType: IApplicationHost.GetPhysicalPath()
  fullName: System.Web.Hosting.IApplicationHost.GetPhysicalPath()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Получает физический путь корневого приложения."
  remarks: "GetPhysicalPath впервые появился в [!INCLUDE[net_v35_long](~/add/includes/ajax-current-ext-md.md)]. Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetPhysicalPath ();
    parameters: []
    return:
      type: System.String
      description: "Физический путь к корневому каталогу приложения."
  overload: System.Web.Hosting.IApplicationHost.GetPhysicalPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationHost.GetSiteID
  id: GetSiteID
  parent: System.Web.Hosting.IApplicationHost
  langs:
  - csharp
  name: GetSiteID()
  nameWithType: IApplicationHost.GetSiteID()
  fullName: System.Web.Hosting.IApplicationHost.GetSiteID()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Возвращает идентификатор узла."
  remarks: "GetSiteID впервые появился в [!INCLUDE[net_v35_long](~/add/includes/ajax-current-ext-md.md)]. Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetSiteID ();
    parameters: []
    return:
      type: System.String
      description: "Идентификатор узла."
  overload: System.Web.Hosting.IApplicationHost.GetSiteID*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationHost.GetSiteName
  id: GetSiteName
  parent: System.Web.Hosting.IApplicationHost
  langs:
  - csharp
  name: GetSiteName()
  nameWithType: IApplicationHost.GetSiteName()
  fullName: System.Web.Hosting.IApplicationHost.GetSiteName()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Получает имя узла."
  remarks: "GetSiteName впервые появился в [!INCLUDE[net_v35_long](~/add/includes/ajax-current-ext-md.md)]. Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetSiteName ();
    parameters: []
    return:
      type: System.String
      description: "Имя сайта."
  overload: System.Web.Hosting.IApplicationHost.GetSiteName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationHost.GetVirtualPath
  id: GetVirtualPath
  parent: System.Web.Hosting.IApplicationHost
  langs:
  - csharp
  name: GetVirtualPath()
  nameWithType: IApplicationHost.GetVirtualPath()
  fullName: System.Web.Hosting.IApplicationHost.GetVirtualPath()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Получает виртуальный путь корневого приложения."
  remarks: "GetVirtualPath впервые появился в [!INCLUDE[net_v35_long](~/add/includes/ajax-current-ext-md.md)]. Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetVirtualPath ();
    parameters: []
    return:
      type: System.String
      description: "Корневой виртуальный путь приложения."
  overload: System.Web.Hosting.IApplicationHost.GetVirtualPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationHost.MessageReceived
  id: MessageReceived
  parent: System.Web.Hosting.IApplicationHost
  langs:
  - csharp
  name: MessageReceived()
  nameWithType: IApplicationHost.MessageReceived()
  fullName: System.Web.Hosting.IApplicationHost.MessageReceived()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Указывает, что сообщение было получено."
  remarks: "MessageReceived впервые появился в [!INCLUDE[net_v35_long](~/add/includes/ajax-current-ext-md.md)]. Дополнительные сведения см. в разделе [версии и зависимости](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void MessageReceived ();
    parameters: []
  overload: System.Web.Hosting.IApplicationHost.MessageReceived*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Hosting.IApplicationHost.GetConfigMapPathFactory
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetConfigMapPathFactory()
  nameWithType: IApplicationHost.GetConfigMapPathFactory()
  fullName: System.Web.Hosting.IApplicationHost.GetConfigMapPathFactory()
- uid: System.Web.Configuration.IConfigMapPathFactory
  parent: System.Web.Configuration
  isExternal: false
  name: IConfigMapPathFactory
  nameWithType: IConfigMapPathFactory
  fullName: System.Web.Configuration.IConfigMapPathFactory
- uid: System.Web.Hosting.IApplicationHost.GetConfigToken
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetConfigToken()
  nameWithType: IApplicationHost.GetConfigToken()
  fullName: System.Web.Hosting.IApplicationHost.GetConfigToken()
- uid: System.IntPtr
  parent: System
  isExternal: true
  name: IntPtr
  nameWithType: IntPtr
  fullName: System.IntPtr
- uid: System.Web.Hosting.IApplicationHost.GetPhysicalPath
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetPhysicalPath()
  nameWithType: IApplicationHost.GetPhysicalPath()
  fullName: System.Web.Hosting.IApplicationHost.GetPhysicalPath()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Hosting.IApplicationHost.GetSiteID
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetSiteID()
  nameWithType: IApplicationHost.GetSiteID()
  fullName: System.Web.Hosting.IApplicationHost.GetSiteID()
- uid: System.Web.Hosting.IApplicationHost.GetSiteName
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetSiteName()
  nameWithType: IApplicationHost.GetSiteName()
  fullName: System.Web.Hosting.IApplicationHost.GetSiteName()
- uid: System.Web.Hosting.IApplicationHost.GetVirtualPath
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetVirtualPath()
  nameWithType: IApplicationHost.GetVirtualPath()
  fullName: System.Web.Hosting.IApplicationHost.GetVirtualPath()
- uid: System.Web.Hosting.IApplicationHost.MessageReceived
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: MessageReceived()
  nameWithType: IApplicationHost.MessageReceived()
  fullName: System.Web.Hosting.IApplicationHost.MessageReceived()
- uid: System.Web.Hosting.IApplicationHost.GetConfigMapPathFactory*
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetConfigMapPathFactory
  nameWithType: IApplicationHost.GetConfigMapPathFactory
- uid: System.Web.Hosting.IApplicationHost.GetConfigToken*
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetConfigToken
  nameWithType: IApplicationHost.GetConfigToken
- uid: System.Web.Hosting.IApplicationHost.GetPhysicalPath*
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetPhysicalPath
  nameWithType: IApplicationHost.GetPhysicalPath
- uid: System.Web.Hosting.IApplicationHost.GetSiteID*
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetSiteID
  nameWithType: IApplicationHost.GetSiteID
- uid: System.Web.Hosting.IApplicationHost.GetSiteName*
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetSiteName
  nameWithType: IApplicationHost.GetSiteName
- uid: System.Web.Hosting.IApplicationHost.GetVirtualPath*
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: GetVirtualPath
  nameWithType: IApplicationHost.GetVirtualPath
- uid: System.Web.Hosting.IApplicationHost.MessageReceived*
  parent: System.Web.Hosting.IApplicationHost
  isExternal: false
  name: MessageReceived
  nameWithType: IApplicationHost.MessageReceived
