### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyNotFoundException
  id: SettingsPropertyNotFoundException
  children:
  - System.Configuration.SettingsPropertyNotFoundException.#ctor
  - System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String)
  - System.Configuration.SettingsPropertyNotFoundException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SettingsPropertyNotFoundException
  nameWithType: SettingsPropertyNotFoundException
  fullName: System.Configuration.SettingsPropertyNotFoundException
  type: Class
  summary: "Предоставляет исключение для <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> объектов, которые не найдены."
  remarks: "Это исключение генерируется <xref:System.Configuration.SettingsBase>класс, при попытке доступа к свойству по имени, но либо свойство никогда не был связан с <xref:System.Configuration.SettingsBase>экземпляра класса или поставщик, сконфигурированный для свойства, не возвратил значения при запросе для загрузки данных свойства.</xref:System.Configuration.SettingsBase> </xref:System.Configuration.SettingsBase>"
  syntax:
    content: 'public class SettingsPropertyNotFoundException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException()
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;></xref> class."
  syntax:
    content: public SettingsPropertyNotFoundException ();
    parameters: []
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException(String)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> класса, на основе предоставленного параметра."
  syntax:
    content: public SettingsPropertyNotFoundException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Строка, содержащая сообщение об исключении."
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> класса, на основе предоставленных параметров."
  syntax:
    content: protected SettingsPropertyNotFoundException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> Объект, содержащий сериализованные данные объекта о вызываемом исключении."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>Объект, содержащий контекстные сведения об источнике или назначении сериализованного потока.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException(String,Exception)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> класса, на основе предоставленных параметров."
  syntax:
    content: public SettingsPropertyNotFoundException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Строка, содержащая сообщение об исключении."
    - id: innerException
      type: System.Exception
      description: "Исключение, которое стало причиной текущего исключения."
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException()
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String)
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException(String)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String,System.Exception)
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException(String,Exception)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException
