### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  id: CompatibleFrameworkCollection
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(System.Int32)
  langs:
  - csharp
  name: CompatibleFrameworkCollection
  nameWithType: CompatibleFrameworkCollection
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  type: Class
  summary: "Представляет коллекцию версий платформы .NET Framework, предпочтительно выполнение приложения."
  remarks: "Если приложение может выполняться в нескольких версиях платформы .NET Framework, версии должен быть указаны в порядке приоритета от наиболее предпочтительный до менее предпочитаемого. Если версии платформы .NET Framework, перечисленных в классе CompatibleFrameworkCollection установлен на компьютере конечного пользователя, приложение можно установить и запустить."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class CompatibleFrameworkCollection : System.Collections.IEnumerable
  inheritance:
  - System.Object
  implements:
  - System.Collections.IEnumerable
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  id: Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Add(CompatibleFramework)
  nameWithType: CompatibleFrameworkCollection.Add(CompatibleFramework)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(CompatibleFramework)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Добавляет платформу для <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework&quot;> </xref> класса."
  syntax:
    content: public void Add (Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework compatibleFramework);
    parameters:
    - id: compatibleFramework
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
      description: "Платформа для добавления."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear
  id: Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: CompatibleFrameworkCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Очищает коллекцию."
  syntax:
    content: public void Clear ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  id: Count
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Count
  nameWithType: CompatibleFrameworkCollection.Count
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Возвращает номер версии платформы .NET Framework, перечисленных в <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection&quot;> </xref> коллекции."
  syntax:
    content: public int Count { get; }
    return:
      type: System.Int32
      description: "Объект <xref:System.Int32>объект, который представляет номер версии платформы .NET Framework перечислены в <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection&quot;> </xref> коллекции.</xref:System.Int32>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator
  id: GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: CompatibleFrameworkCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Возвращает перечислитель для коллекции."
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: "A <xref:System.Collections.IEnumerator>интерфейс, который может выполнять итерацию по коллекции.</xref:System.Collections.IEnumerator>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: CompatibleFrameworkCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(Int32)
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Получает версию платформы .NET Framework, предпочтительно выполнение приложения."
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "Версия .NET Framework для проверки на компьютере конечного пользователя."
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
      description: "Объект <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework&quot;> </xref> объект, представляющий версии платформы .NET Framework, предпочтительно выполнение приложения."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Add(CompatibleFramework)
  nameWithType: CompatibleFrameworkCollection.Add(CompatibleFramework)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(CompatibleFramework)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Clear()
  nameWithType: CompatibleFrameworkCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Count
  nameWithType: CompatibleFrameworkCollection.Count
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: CompatibleFrameworkCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: CompatibleFrameworkCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(Int32)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Add
  nameWithType: CompatibleFrameworkCollection.Add
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Clear
  nameWithType: CompatibleFrameworkCollection.Clear
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Count
  nameWithType: CompatibleFrameworkCollection.Count
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: GetEnumerator
  nameWithType: CompatibleFrameworkCollection.GetEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Item
  nameWithType: CompatibleFrameworkCollection.Item
